#!/usr/bin/env python3
"""Untrusted generator for PCS/V2/Golden/FileLiterals.lean.

Reads the *committed* golden fixture files byte-for-byte and prints them as Lean literals,
together with their SHA-256 digests (hashlib) and CRC-32 checkpoint tables (zlib) for every
archive member.  Nothing printed here is trusted by the proofs:

* `PCS.V2.Golden.ArchiveBytes` proves in the kernel that the archive literal *is* the
  canonical encoding of the golden entries (`goldenRaw`), that every CRC checkpoint is
  correct, and that the transcript literal is the canonical golden transcript;
* a wrong literal makes those proofs fail.  (The SHA-256 digest literals are informational
  only and are not used by any proof.)

The only link that is not a Lean proof is "this literal equals the bytes of the file on
disk", which `tools/CheckGoldenFileLiterals.lean` re-checks by reading the committed files
and comparing them byte for byte with the literals.

Usage: python3 tools/gen_golden_file_literals.py > PCS/V2/Golden/FileLiterals.lean
"""
import hashlib, os, struct, sys, zlib

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "fixtures", "ai_safety_golden")
CHUNK = 64


def chunked(xs):
    out = []
    for i, x in enumerate(xs):
        if i > 0:
            out.append(",\n    " if i % 24 == 0 else ", ")
        out.append(str(x))
    return "".join(out)


def bytes_def(name, doc, bs):
    return f"/-- {doc} -/\ndef {name} : List UInt8 :=\n  [{chunked(list(bs))}]\n"


def parts_def(name, doc, bs, size=1024):
    """Long byte strings are split into parts (a single 7.7 KB list literal exceeds the
    elaborator's recursion limit)."""
    names, out = [], []
    for k, i in enumerate(range(0, len(bs), size)):
        names.append(f"{name}Part{k}")
        out.append(bytes_def(f"{name}Part{k}", f"part {k} of `{name}`", bs[i:i + size]))
    out.append(f"/-- {doc} -/\ndef {name} : List UInt8 :=\n  {' ++ '.join(names)}\n")
    return "\n".join(out)


def crc_chunks_def(name, doc, data):
    parts = []
    for i in range(0, len(data), CHUNK):
        c = data[i:i + CHUNK]
        state = zlib.crc32(data[:i + CHUNK]) ^ 0xFFFFFFFF
        parts.append(f"  ([{', '.join(str(b) for b in c)}], {state})")
    if not parts:
        parts.append(f"  ([], {0xFFFFFFFF})")
    body = ",\n".join(parts)
    return f"/-- {doc} -/\ndef {name} : List (List UInt8 × UInt32) := [\n{body}]\n"


def members(raw):
    """Parse the local headers of a STORED zip (names and data), in archive order."""
    out, pos = [], 0
    while raw[pos:pos + 4] == b"PK\x03\x04":
        (sig, ver, flags, meth, t, d, crc, csz, usz, nlen, xlen) = struct.unpack("<IHHHHHIIIHH", raw[pos:pos + 30])
        name = raw[pos + 30:pos + 30 + nlen].decode("utf-8")
        start = pos + 30 + nlen + xlen
        out.append((name, raw[start:start + csz], crc))
        pos = start + csz
    return out


def main():
    raw = open(os.path.join(ROOT, "archive.zip"), "rb").read()
    obs = open(os.path.join(ROOT, "observations.json"), "rb").read()
    pk = open(os.path.join(ROOT, "pk.b64")).read().strip()
    fp = open(os.path.join(ROOT, "fingerprint.hex")).read().strip()
    w = sys.stdout.write
    w("/-! Byte literals of the committed golden fixture files (generated by\n"
      "`tools/gen_golden_file_literals.py` from `fixtures/ai_safety_golden/`; **untrusted**:\n"
      "see `PCS.V2.Golden.ArchiveBytes` for the kernel-checked facts about them). -/\n\n"
      "set_option autoImplicit false\n\nnamespace PCS.V2.Golden.FileLit\n\n")
    w(parts_def("archiveBytes", "bytes of `fixtures/ai_safety_golden/archive.zip`", raw) + "\n")
    w(bytes_def("archiveSha256", "SHA-256 of `archive.zip` (hashlib)", hashlib.sha256(raw).digest()) + "\n")
    w(bytes_def("observationsBytes", "bytes of `fixtures/ai_safety_golden/observations.json`", obs) + "\n")
    w(bytes_def("observationsSha256", "SHA-256 of `observations.json` (hashlib)", hashlib.sha256(obs).digest()) + "\n")
    w(f"/-- contents of `pk.b64` (trimmed) -/\ndef pkB64 : String := \"{pk}\"\n\n")
    w(f"/-- contents of `fingerprint.hex` (trimmed) -/\ndef fingerprintHex : String := \"{fp}\"\n\n")
    for i, (name, data, crc) in enumerate(members(raw)):
        assert zlib.crc32(data) == crc
        w(crc_chunks_def(f"crcChunks{i}", f"CRC-32 checkpoints of member `{name}` ({len(data)} bytes)", data) + "\n")
    w("end PCS.V2.Golden.FileLit\n")


if __name__ == "__main__":
    main()
