#!/usr/bin/env python3
"""Regenerate PCS/V2/SemanticV3Audit.lean: one `#print axioms` line for every theorem of the
Proof-Carrying Semantic Intelligence v3 modules (run from the project root).  Namespaces are
tracked from `namespace`/`end` lines."""
import re

FILES = ['ReceiptAuthorityV3', 'TranslationV3', 'ReceiptThreatModelV3', 'TranslationV3Json',
         'LeanSyntaxV3', 'AssuranceV3', 'EntailmentV3', 'CertiForgeAdapterV1']

out = ["\n".join("import PCS.V2.%s" % f for f in FILES), "",
       "/-! Axiom audit of PCS Proof-Carrying Semantic Intelligence v3 (printed on every build).",
       "    Every theorem of the v3 modules is listed.  Expected: only `propext`, `Classical.choice`,",
       "    `Quot.sound` (or a subset); never `sorryAx`, `Lean.ofReduceBool` or a project axiom.",
       "    Checked mechanically by tools/check_semantic_v3_audit.sh.",
       "    Generated by tools/gen_semantic_v3_audit.py. -/", ""]
n = 0
for f in FILES:
    out.append("-- %s" % f)
    stack = []
    for line in open('PCS/V2/%s.lean' % f, encoding='utf-8'):
        m = re.match(r'namespace (\S+)', line)
        if m:
            stack.append(m.group(1))
            continue
        m = re.match(r'end (\S+)', line)
        if m and stack and stack[-1] == m.group(1):
            stack.pop()
            continue
        m = re.match(r'theorem (\S+)', line)
        if m:
            name = m.group(1)
            ns = ".".join(stack)
            full = name[7:] if name.startswith('_root_.') else (ns + '.' + name if ns else name)
            out.append("#print axioms %s" % full)
            n += 1
open('PCS/V2/SemanticV3Audit.lean', 'w', encoding='utf-8').write("\n".join(out) + "\n")
print(f"{n} theorems")
