#!/usr/bin/env python3
"""Regenerate PCS/V2/SemanticV2Audit.lean: one `#print axioms` line for every theorem of the
Semantic Intelligence v2 modules (run from the project root)."""
import re

FILES = {'SemanticEquiv': 'PCS.V2.Semantic', 'FiniteModel': 'PCS.V2.Semantic',
         'CertSearch': 'PCS.V2.Semantic', 'TranslationV2': 'PCS.V2.Semantic',
         'TranslationV2Json': 'PCS.V2.Semantic', 'SemanticFeedback': 'PCS.V2.Semantic',
         'SemanticLimits': 'PCS.V2.Semantic.Limits', 'SemanticV2Fixtures': 'PCS.V2.Semantic.FixturesV2',
         'SemanticCompose': 'PCS.V2.Semantic', 'ReceiptLedger': 'PCS.V2.Semantic.Ledger',
         'CNL': 'PCS.V2.Semantic.CNL', 'SemanticV2LeanModel': 'PCS.V2.Semantic.LeanModel'}

out = ["\n".join("import PCS.V2.%s" % f for f in FILES), "",
       "/-! Axiom audit of PCS Proof-Carrying Semantic Intelligence v2 (printed on every build).",
       "    Every theorem of the v2 modules is listed.  Expected: only `propext`, `Classical.choice`,",
       "    `Quot.sound` (or a subset); never `sorryAx`, `Lean.ofReduceBool` or a project axiom.",
       "    Generated by tools/gen_semantic_v2_audit.py. -/", ""]
n = 0
for f, ns in FILES.items():
    out.append("-- %s" % f)
    for line in open('PCS/V2/%s.lean' % f):
        m = re.match(r'theorem (\S+)', line)
        if m:
            name = m.group(1)
            full = name[7:] if name.startswith('_root_.') else ns + '.' + name
            out.append("#print axioms %s" % full)
            n += 1
open('PCS/V2/SemanticV2Audit.lean', 'w').write("\n".join(out) + "\n")
print(f"{n} theorems")
