import PCS.V2.GoldenCx.Spec

/-! Untrusted generator for `PCS/V2/GoldenCx/Literals.lean`: prints the precomputed digests,
    signed messages and member bytes of the counterexample (uncertified tag) fixture as Lean literals.
    Every literal is re-derived from the fixture builder by a kernel-checked theorem in
    `PCS.V2.GoldenCx.Provenance`, so this generator is *not* trusted.
    Usage: `lake env lean --run tools/GenCxLiterals.lean > PCS/V2/GoldenCx/Literals.lean` -/

open PCS.V2.Witnesses.AISafetyGolden PCS.V2.Index PCS.V2.CertificateModel

def chunked (xs : List Nat) : String := Id.run do
  let mut out := ""
  let mut i := 0
  for x in xs do
    if i > 0 then
      out := out ++ (if i % 24 == 0 then ",\n    " else ", ")
    out := out ++ toString x
    i := i + 1
  return out

def bytesDef (name doc : String) (xs : List UInt8) : String :=
  s!"/-- {doc} -/\ndef {name} : List UInt8 :=\n  [{chunked (xs.map UInt8.toNat)}]\n"

def main : IO Unit := do
  let s := PCS.V2.GoldenCx.cx
  IO.println "/-! Precomputed literals of the counterexample (uncertified tag) fixture (generated by
`tools/GenCxLiterals.lean`; **untrusted**: each literal is proved equal to the value
computed by the fixture builder in `PCS.V2.GoldenCx.Provenance`). -/

namespace PCS.V2.GoldenCx.Lit
"
  IO.println (bytesDef "traceDigest" "SHA-256 of the committed trace bytes" (PCS.V2.SHA256.sha256 s.trace.data.toList))
  IO.println (bytesDef "semHash" "certificate semantic hash" s.semHash)
  IO.println (bytesDef "intHash" "certificate integrity hash" s.intHash)
  IO.println (bytesDef "commitment" "predicate commitment of the claim/evidence predicate" (commitmentOf (predJ 4 7)))
  IO.println (bytesDef "storageKeyC1" "normalized storage key of claim `C1`" (storageKey "C1"))
  IO.println (bytesDef "wireHash" "normalized wire semantic hash" s.wire.wireSemanticHash)
  IO.println (bytesDef "indexHash" "normalized index semantic hash" s.index.indexSemanticHash)
  IO.println (bytesDef "fingerprint" "SHA-256 fingerprint of the RFC 8032 TEST 1 public key" (PCS.V2.Signature.fingerprintOf testPk))
  IO.println (bytesDef "certBytes" "`certificate.json` bytes" s.certBytes.data.toList)
  IO.println (bytesDef "wireBytes" "normalized wire member bytes" s.wireBytes.data.toList)
  IO.println (bytesDef "indexBytes" "`normalized/index.json` bytes" s.indexBytes.data.toList)
  IO.println (bytesDef "certDigest" "SHA-256 of `certificate.json`" (PCS.V2.SHA256.sha256 s.certBytes.data.toList))
  IO.println (bytesDef "wireDigest" "SHA-256 of the normalized wire member" (PCS.V2.SHA256.sha256 s.wireBytes.data.toList))
  IO.println (bytesDef "indexDigest" "SHA-256 of `normalized/index.json`" (PCS.V2.SHA256.sha256 s.indexBytes.data.toList))
  IO.println (bytesDef "manifestBytes" "`package_manifest.json` bytes" s.manifestBytes.data.toList)
  IO.println (bytesDef "certMsg" "exact message signed by the certificate signature" s.certMsg)
  IO.println (bytesDef "pkgMsg" "exact message signed by the package signature" s.pkgMsg)
  IO.println (bytesDef "certMsgDigest" "SHA-256 of the certificate-signature message" (PCS.V2.SHA256.sha256 s.certMsg))
  IO.println (bytesDef "pkgMsgDigest" "SHA-256 of the package-signature message" (PCS.V2.SHA256.sha256 s.pkgMsg))
  IO.println (bytesDef "certSigBytes" "`certificate_signature.json` bytes" (s.certSigBytesWith PCS.V2.GoldenCx.cxCertSig).data.toList)
  IO.println (bytesDef "pkgSigBytes" "`package_signature.json` bytes" (s.pkgSigBytesWith PCS.V2.GoldenCx.cxPkgSig).data.toList)
  IO.println "end PCS.V2.GoldenCx.Lit"
