import PCSOmega
import PCSOmega.Controls
import PCSDecisionDiagram
import PCSDecisionDiagram.Controls

/-! Integration audit of every named positive theorem in the returned libraries. -/

#print axioms PCSDD.BOp.app_comm
#print axioms PCSDD.findNode_some
#print axioms PCSDD.findNode_none
#print axioms PCSDD.Inv.empty
#print axioms PCSDD.MemoOK.extend
#print axioms PCSDD.mkNode_spec
#print axioms PCSDD.memoLookup_mem
#print axioms PCSDD.evalD_terminal
#print axioms PCSDD.termOp_spec
#print axioms PCSDD.cof_spec
#print axioms PCSDD.topVar_lt_of_ge2
#print axioms PCSDD.apply_spec
#print axioms PCSDD.apply_ops_le
#print axioms PCSDD.apply_exhausted
#print axioms PCSDD.Inv.visits
#print axioms PCSDD.Inv.wsteps
#print axioms PCSDD.compile_spec
#print axioms PCSDD.cellRec_zero
#print axioms PCSDD.cellRec_one
#print axioms PCSDD.cellRec_node
#print axioms PCSDD.mem_candL
#print axioms PCSDD.branch_split
#print axioms PCSDD.candL_split
#print axioms PCSDD.summ_branch
#print axioms PCSDD.comb_bcell_skip
#print axioms PCSDD.summ_cellRec
#print axioms PCSDD.Denotes.extend
#print axioms PCSDD.RootsOK.extend
#print axioms PCSDD.allEval_append
#print axioms PCSDD.allEval_take
#print axioms PCSDD.conjList_spec
#print axioms PCSDD.denotes_one
#print axioms PCSDD.premLoop_spec
#print axioms PCSDD.allEval_pick_iff
#print axioms PCSDD.RootsOK.pick
#print axioms PCSDD.SatSet.mono
#print axioms PCSDD.shrink_spec
#print axioms PCSDD.coreWits_spec
#print axioms PCSDD.verify_iff
#print axioms PCSDD.check_flags
#print axioms PCSDD.check_resource_limit
#print axioms PCSDD.premAt_eq
#print axioms PCSDD.pipeline_premises
#print axioms PCSDD.check_inconsistent
#print axioms PCSDD.pipeline_decided
#print axioms PCSDD.check_equivalent
#print axioms PCSDD.check_counterexample
#print axioms PCSDD.Controls.tAB_equivalent
#print axioms PCSDD.Controls.tOpp_inconsistent
#print axioms PCSDD.Controls.dm24_decision
#print axioms PCSDD.Controls.dm24_equivalent
#print axioms PCSDD.Controls.tDense_nothing_claimed
#print axioms PCSDD.Controls.lockBoth_infeasible
#print axioms PCSDD.Controls.choices12_summary
#print axioms PCSDD.evalD_zero
#print axioms PCSDD.evalD_one
#print axioms PCSDD.getNode_idx
#print axioms PCSDD.getNode_lt
#print axioms PCSDD.getNode_none_of_ge
#print axioms PCSDD.evalD_node
#print axioms PCSDD.Valid.node
#print axioms PCSDD.topVar_le
#print axioms PCSDD.topVar_terminal
#print axioms PCSDD.topVar_node
#print axioms PCSDD.evalD_support
#print axioms PCSDD.evalD_shannon
#print axioms PCSDD.Extends.refl
#print axioms PCSDD.Extends.trans
#print axioms PCSDD.Extends.push
#print axioms PCSDD.Extends.getNode
#print axioms PCSDD.Extends.topVar
#print axioms PCSDD.evalD_extend
#print axioms PCSDD.exists_sat_unsat
#print axioms PCSDD.eq_zero_iff_unsat
#print axioms PCSDD.eq_one_iff_valid
#print axioms PCSDD.getNode_some_of_ge2
#print axioms PCSDD.children_agree
#print axioms PCSDD.children_agree_same
#print axioms PCSDD.canonical
#print axioms PCSDD.canonical'
#print axioms PCSDD.IReceipt.verify_iff
#print axioms PCSDD.IReceipt.verify_rejects
#print axioms PCSDD.IReceipt.verify_rejects_changed
#print axioms PCSDD.strictSorted_nodup
#print axioms PCSDD.validFacts
#print axioms PCSDD.check_decided
#print axioms PCSDD.feasible_iff
#print axioms PCSDD.optimal_iff
#print axioms PCSDD.guard_iff
#print axioms PCSDD.plan_valid
#print axioms PCSDD.plan_cases
#print axioms PCSDD.plan_ok
#print axioms PCSDD.plan_resource_limit
#print axioms PCSDD.plan_inconsistent
#print axioms PCSDD.plan_no_feasible
#print axioms PCSDD.plan_optimal
#print axioms PCSDD.plan_flags
#print axioms PCSDD.js_safe_bounds
#print axioms PCSDD.audit_unfold
#print axioms PCSDD.audit_feasible_iff
#print axioms PCSDD.audit_gap
#print axioms PCSDD.audit_no_gap_unresolved
#print axioms PCSDD.audit_no_gap_infeasible
#print axioms PCSDD.audit_gap_present
#print axioms PCSDD.objL_eq
#print axioms PCSDD.objL_zero
#print axioms PCSDD.testBit_maskL
#print axioms PCSDD.maskL_zero_testBit
#print axioms PCSDD.locksB_iff
#print axioms PCSDD.feasL_zero_iff
#print axioms PCSDD.mem_candL_zero
#print axioms PCSDD.summ_root
#print axioms PCSDD.bellman_correct
#print axioms PCSDD.objective_le
#print axioms PCSDD.bellman_bounds
#print axioms PCSDD.winnersCell_two
#print axioms PCSDD.inspect_eq
#print axioms PCSDD.stepCell_eq
#print axioms PCSDD.passUpTo_inv
#print axioms PCSDD.bellmanPass_spec
#print axioms PCSDD.choiceRec_node
#print axioms PCSDD.chosen_child_some
#print axioms PCSDD.walkPy_level
#print axioms PCSDD.walkPy_spec
#print axioms PCSDD.summ_min
#print axioms PCSDD.summ_none
#print axioms PCSDD.optC_cons
#print axioms PCSDD.optC_skip_iff
#print axioms PCSDD.comb_cost_le
#print axioms PCSDD.comb_lt
#print axioms PCSDD.bcell_some
#print axioms PCSDD.recon_least
#print axioms PCSDD.recon_spec
#print axioms PCSDD.Summ.nil
#print axioms PCSDD.Summ.single
#print axioms PCSDD.Summ.unique
#print axioms PCSDD.noneIff_of_some
#print axioms PCSDD.Summ.append_lt
#print axioms PCSDD.Summ.perm_append
#print axioms PCSDD.Summ.append
#print axioms PCSDD.Summ.shift
#print axioms PCSDD.shiftCell_zero
#print axioms PCSDD.shiftP_zero
#print axioms PCSDD.comb_shift_pos
#print axioms PCSDD.validB_iff
#print axioms PCSDD.bellmanChecked_ok
#print axioms PCSDD.envL_zero
#print axioms PCSDD.envL_cons_self
#print axioms PCSDD.envL_cons_succ
#print axioms PCSDD.evalD_skip
#print axioms PCSDD.evalD_level_node
#print axioms PCSDD.terminal_of_topVar
#print axioms PCSDD.wit_eq
#print axioms PCSDD.wit_length
#print axioms PCSDD.wit_least
#print axioms PCSDD.satL_zero_iff
#print axioms PCSDD.world_spec
#print axioms PCSDD.witSteps_eq
#print axioms PCSDD.witSteps_le
#print axioms PCSOmega.disagree_iff
#print axioms PCSOmega.semEquiv_iff_lists
#print axioms PCSOmega.check_none_iff
#print axioms PCSOmega.check_some_sound
#print axioms PCSOmega.check_some_least
#print axioms PCSOmega.checkReceipt_equivalent_iff
#print axioms PCSOmega.checkReceipt_count
#print axioms PCSOmega.checkReceipt_flags
#print axioms PCSOmega.verifyCheckReceipt_iff
#print axioms PCSOmega.screen_some_not_equiv
#print axioms PCSOmega.screen_append_of_some
#print axioms PCSOmega.screen_isSome_append_left
#print axioms PCSOmega.screen_none_of_equiv
#print axioms PCSOmega.Controls.implication_reversal_not_equiv
#print axioms PCSOmega.Controls.de_morgan_equiv
#print axioms PCSOmega.Controls.remembered_rejection
#print axioms PCSOmega.Controls.screen_survivor_not_equiv
#print axioms PCSOmega.Controls.episode_solution_sound
#print axioms PCSOmega.BForm.eval_iff_holds
#print axioms PCSOmega.BForm.eval_congr
#print axioms PCSOmega.listOf_length
#print axioms PCSOmega.envOf_listOf
#print axioms PCSOmega.allAsg_zero
#print axioms PCSOmega.mem_allAsg
#print axioms PCSOmega.length_allAsg
#print axioms PCSOmega.nodup_allAsg
#print axioms PCSOmega.lexLt_irrefl
#print axioms PCSOmega.lexLt_trans
#print axioms PCSOmega.lexLt_total
#print axioms PCSOmega.pairwise_lexLt_allAsg
#print axioms PCSOmega.IsLexLeast.unique
#print axioms PCSOmega.find?_pairwise_least
#print axioms PCSOmega.isLexLeast_cons_false
#print axioms PCSOmega.isLexLeast_cons_true
#print axioms PCSOmega.strictSortedS_head_lt
#print axioms PCSOmega.strictSortedS_nodup
#print axioms PCSOmega.lower_eval
#print axioms PCSOmega.idxOf?_isSome_iff
#print axioms PCSOmega.idxOf?_lt
#print axioms PCSOmega.lower_isSome_iff
#print axioms PCSOmega.lower_size_depth
#print axioms PCSOmega.applyAction_bounded
#print axioms PCSOmega.actionsAux_length
#print axioms PCSOmega.actionsOf_length
#print axioms PCSOmega.screenWork_fst
#print axioms PCSOmega.screenWork_snd_le
#print axioms PCSOmega.expand_solution
#print axioms PCSOmega.remember_solution
#print axioms PCSOmega.examine_solInv
#print axioms PCSOmega.loop_solInv
#print axioms PCSOmega.initState_solInv
#print axioms PCSOmega.search_solution_sound
#print axioms PCSOmega.search_status_iff
#print axioms PCSOmega.search_flags
#print axioms PCSOmega.expand_fields
#print axioms PCSOmega.recordAttempt_fields
#print axioms PCSOmega.remember_fields
#print axioms PCSOmega.examine_accInv
#print axioms PCSOmega.loop_accInv
#print axioms PCSOmega.initState_accInv
#print axioms PCSOmega.search_accounting
#print axioms PCSOmega.search_checksUsed_eq
#print axioms PCSOmega.finishChecked_sol
#print axioms PCSOmega.finishChecked_sol'
#print axioms PCSOmega.replayRow_inv
#print axioms PCSOmega.replayRows_inv
#print axioms PCSOmega.replay_sound
