-- Generated by scripts/generate_countermodel_missions.py; checked in CI.
import PCSCountermodel.Fixtures

namespace PCSCountermodel.Missions
def rulesetSHA256 : String := "d3b02eb4eb39976fd3179a44ef1b6bffd17a8f4a271b1bd7cddb97eb71276df2"

-- quantifier-switch
def leftN0 : NFormula := (.all "x" (.imp (.pred "P" "x") (.pred "Q" "x")))
def rightN0 : NFormula := (.ex "x" (.imp (.pred "P" "x") (.pred "Q" "x")))
def left0 : Formula 0 := (.all (.imp (.pred .P 0) (.pred .Q 0)))
def right0 : Formula 0 := (.ex (.imp (.pred .P 0) (.pred .Q 0)))
theorem lowering0 : lower [] leftN0 = some left0 ∧
    lower [] rightN0 = some right0 := ⟨rfl, rfl⟩
theorem witness0 : checker (worldOfBits 2 1) left0 right0 = true := by decide
theorem disagreement0 (ρ : String → Fin 2) :
    ¬ (NHolds (worldOfBits 2 1) ρ leftN0 ↔
       NHolds (worldOfBits 2 1) ρ rightN0) :=
  (namedChecker_sound _ (c := true) (by decide) ρ).mp rfl
theorem minimum0 : (search left0 right0).map Sigma.fst = some 2 := by decide

-- negation-drop
def leftN1 : NFormula := (.all "x" (.imp (.pred "P" "x") (.not (.pred "Q" "x"))))
def rightN1 : NFormula := (.all "x" (.imp (.pred "P" "x") (.pred "Q" "x")))
def left1 : Formula 0 := (.all (.imp (.pred .P 0) (.not (.pred .Q 0))))
def right1 : Formula 0 := (.all (.imp (.pred .P 0) (.pred .Q 0)))
theorem lowering1 : lower [] leftN1 = some left1 ∧
    lower [] rightN1 = some right1 := ⟨rfl, rfl⟩
theorem witness1 : checker (worldOfBits 1 1) left1 right1 = true := by decide
theorem disagreement1 (ρ : String → Fin 1) :
    ¬ (NHolds (worldOfBits 1 1) ρ leftN1 ↔
       NHolds (worldOfBits 1 1) ρ rightN1) :=
  (namedChecker_sound _ (c := true) (by decide) ρ).mp rfl
theorem minimum1 : (search left1 right1).map Sigma.fst = some 1 := by decide

-- implication-flip
def leftN2 : NFormula := (.all "x" (.imp (.pred "P" "x") (.pred "Q" "x")))
def rightN2 : NFormula := (.all "x" (.imp (.pred "Q" "x") (.pred "P" "x")))
def left2 : Formula 0 := (.all (.imp (.pred .P 0) (.pred .Q 0)))
def right2 : Formula 0 := (.all (.imp (.pred .Q 0) (.pred .P 0)))
theorem lowering2 : lower [] leftN2 = some left2 ∧
    lower [] rightN2 = some right2 := ⟨rfl, rfl⟩
theorem witness2 : checker (worldOfBits 1 1) left2 right2 = true := by decide
theorem disagreement2 (ρ : String → Fin 1) :
    ¬ (NHolds (worldOfBits 1 1) ρ leftN2 ↔
       NHolds (worldOfBits 1 1) ρ rightN2) :=
  (namedChecker_sound _ (c := true) (by decide) ρ).mp rfl
theorem minimum2 : (search left2 right2).map Sigma.fst = some 1 := by decide

-- connective-swap
def leftN3 : NFormula := (.ex "x" (.and (.pred "P" "x") (.pred "Q" "x")))
def rightN3 : NFormula := (.ex "x" (.or (.pred "P" "x") (.pred "Q" "x")))
def left3 : Formula 0 := (.ex (.and (.pred .P 0) (.pred .Q 0)))
def right3 : Formula 0 := (.ex (.or (.pred .P 0) (.pred .Q 0)))
theorem lowering3 : lower [] leftN3 = some left3 ∧
    lower [] rightN3 = some right3 := ⟨rfl, rfl⟩
theorem witness3 : checker (worldOfBits 1 1) left3 right3 = true := by decide
theorem disagreement3 (ρ : String → Fin 1) :
    ¬ (NHolds (worldOfBits 1 1) ρ leftN3 ↔
       NHolds (worldOfBits 1 1) ρ rightN3) :=
  (namedChecker_sound _ (c := true) (by decide) ρ).mp rfl
theorem minimum3 : (search left3 right3).map Sigma.fst = some 1 := by decide

-- assumption-loss
def leftN4 : NFormula := (.all "x" (.imp (.pred "P" "x") (.pred "Q" "x")))
def rightN4 : NFormula := (.all "x" (.pred "Q" "x"))
def left4 : Formula 0 := (.all (.imp (.pred .P 0) (.pred .Q 0)))
def right4 : Formula 0 := (.all (.pred .Q 0))
theorem lowering4 : lower [] leftN4 = some left4 ∧
    lower [] rightN4 = some right4 := ⟨rfl, rfl⟩
theorem witness4 : checker (worldOfBits 1 0) left4 right4 = true := by decide
theorem disagreement4 (ρ : String → Fin 1) :
    ¬ (NHolds (worldOfBits 1 0) ρ leftN4 ↔
       NHolds (worldOfBits 1 0) ρ rightN4) :=
  (namedChecker_sound _ (c := true) (by decide) ρ).mp rfl
theorem minimum4 : (search left4 right4).map Sigma.fst = some 1 := by decide

-- quantifier-scope
def leftN5 : NFormula := (.all "x" (.ex "y" (.rel "x" "y")))
def rightN5 : NFormula := (.ex "y" (.all "x" (.rel "x" "y")))
def left5 : Formula 0 := (.all (.ex (.rel 1 0)))
def right5 : Formula 0 := (.ex (.all (.rel 0 1)))
theorem lowering5 : lower [] leftN5 = some left5 ∧
    lower [] rightN5 = some right5 := ⟨rfl, rfl⟩
theorem witness5 : checker (worldOfBits 2 144) left5 right5 = true := by decide
theorem disagreement5 (ρ : String → Fin 2) :
    ¬ (NHolds (worldOfBits 2 144) ρ leftN5 ↔
       NHolds (worldOfBits 2 144) ρ rightN5) :=
  (namedChecker_sound _ (c := true) (by decide) ρ).mp rfl
theorem minimum5 : (search left5 right5).map Sigma.fst = some 2 := by decide

-- variable-capture
def leftN6 : NFormula := (.all "x" (.ex "y" (.rel "x" "y")))
def rightN6 : NFormula := (.all "x" (.rel "x" "x"))
def left6 : Formula 0 := (.all (.ex (.rel 1 0)))
def right6 : Formula 0 := (.all (.rel 0 0))
theorem lowering6 : lower [] leftN6 = some left6 ∧
    lower [] rightN6 = some right6 := ⟨rfl, rfl⟩
theorem witness6 : checker (worldOfBits 2 96) left6 right6 = true := by decide
theorem disagreement6 (ρ : String → Fin 2) :
    ¬ (NHolds (worldOfBits 2 96) ρ leftN6 ↔
       NHolds (worldOfBits 2 96) ρ rightN6) :=
  (namedChecker_sound _ (c := true) (by decide) ρ).mp rfl
theorem minimum6 : (search left6 right6).map Sigma.fst = some 2 := by decide

def missions : List (String × NFormula × NFormula) := [
  ("quantifier-switch", leftN0, rightN0),
  ("negation-drop", leftN1, rightN1),
  ("implication-flip", leftN2, rightN2),
  ("connective-swap", leftN3, rightN3),
  ("assumption-loss", leftN4, rightN4),
  ("quantifier-scope", leftN5, rightN5),
  ("variable-capture", leftN6, rightN6)
]
#print axioms lowering0
#print axioms witness0
#print axioms disagreement0
#print axioms minimum0
#print axioms lowering1
#print axioms witness1
#print axioms disagreement1
#print axioms minimum1
#print axioms lowering2
#print axioms witness2
#print axioms disagreement2
#print axioms minimum2
#print axioms lowering3
#print axioms witness3
#print axioms disagreement3
#print axioms minimum3
#print axioms lowering4
#print axioms witness4
#print axioms disagreement4
#print axioms minimum4
#print axioms lowering5
#print axioms witness5
#print axioms disagreement5
#print axioms minimum5
#print axioms lowering6
#print axioms witness6
#print axioms disagreement6
#print axioms minimum6
end PCSCountermodel.Missions
