import PCSOmega
import PCSOmega.Controls
import PCSDecisionDiagram
import PCSDecisionDiagram.Controls

/-! # Axiom audit of the principal Omega / decision-diagram / intervention theorems

Run: `lake env lean PCSOmegaDDAudit.lean`.  Output recorded in `logs/omega-dd-axioms.log`. -/

#print axioms PCSOmega.BForm.eval_iff_holds
#print axioms PCSOmega.BForm.eval_congr
#print axioms PCSOmega.mem_allAsg
#print axioms PCSOmega.length_allAsg
#print axioms PCSOmega.nodup_allAsg
#print axioms PCSOmega.pairwise_lexLt_allAsg
#print axioms PCSOmega.IsLexLeast.unique
#print axioms PCSOmega.check_none_iff
#print axioms PCSOmega.check_some_sound
#print axioms PCSOmega.check_some_least
#print axioms PCSOmega.checkReceipt_equivalent_iff
#print axioms PCSOmega.checkReceipt_count
#print axioms PCSOmega.verifyCheckReceipt_iff
#print axioms PCSOmega.screen_some_not_equiv
#print axioms PCSOmega.screen_append_of_some
#print axioms PCSOmega.screen_isSome_append_left
#print axioms PCSOmega.screen_none_of_equiv
#print axioms PCSOmega.actionsOf_length
#print axioms PCSOmega.applyAction_bounded
#print axioms PCSOmega.search_solution_sound
#print axioms PCSOmega.search_status_iff
#print axioms PCSOmega.search_flags
#print axioms PCSOmega.search_accounting
#print axioms PCSOmega.replay_sound
#print axioms PCSOmega.strictSortedS_nodup
#print axioms PCSOmega.lower_eval
#print axioms PCSOmega.lower_isSome_iff
#print axioms PCSOmega.lower_size_depth
#print axioms PCSOmega.Controls.implication_reversal_not_equiv
#print axioms PCSOmega.Controls.de_morgan_equiv
#print axioms PCSOmega.Controls.remembered_rejection
#print axioms PCSOmega.Controls.screen_survivor_not_equiv
#print axioms PCSOmega.Controls.episode_solution_sound
#print axioms PCSDD.evalD_support
#print axioms PCSDD.evalD_shannon
#print axioms PCSDD.evalD_extend
#print axioms PCSDD.exists_sat_unsat
#print axioms PCSDD.eq_zero_iff_unsat
#print axioms PCSDD.eq_one_iff_valid
#print axioms PCSDD.canonical
#print axioms PCSDD.mkNode_spec
#print axioms PCSDD.apply_spec
#print axioms PCSDD.apply_ops_le
#print axioms PCSDD.apply_exhausted
#print axioms PCSDD.compile_spec
#print axioms PCSDD.wit_least
#print axioms PCSDD.world_spec
#print axioms PCSDD.witSteps_le
#print axioms PCSDD.conjList_spec
#print axioms PCSDD.premLoop_spec
#print axioms PCSDD.shrink_spec
#print axioms PCSDD.coreWits_spec
#print axioms PCSDD.verify_iff
#print axioms PCSDD.check_flags
#print axioms PCSDD.check_resource_limit
#print axioms PCSDD.check_inconsistent
#print axioms PCSDD.check_equivalent
#print axioms PCSDD.check_counterexample
#print axioms PCSDD.Summ.unique
#print axioms PCSDD.Summ.append
#print axioms PCSDD.Summ.shift
#print axioms PCSDD.comb_shift_pos
#print axioms PCSDD.candL_split
#print axioms PCSDD.comb_bcell_skip
#print axioms PCSDD.summ_cellRec
#print axioms PCSDD.bellman_correct
#print axioms PCSDD.bellman_bounds
#print axioms PCSDD.optC_skip_iff
#print axioms PCSDD.recon_least
#print axioms PCSDD.recon_spec
#print axioms PCSDD.winnersCell_two
#print axioms PCSDD.stepCell_eq
#print axioms PCSDD.bellmanPass_spec
#print axioms PCSDD.walkPy_spec
#print axioms PCSDD.validB_iff
#print axioms PCSDD.bellmanChecked_ok
#print axioms PCSDD.plan_valid
#print axioms PCSDD.plan_ok
#print axioms PCSDD.plan_resource_limit
#print axioms PCSDD.plan_inconsistent
#print axioms PCSDD.plan_no_feasible
#print axioms PCSDD.plan_optimal
#print axioms PCSDD.plan_flags
#print axioms PCSDD.js_safe_bounds
#print axioms PCSDD.IReceipt.verify_iff
#print axioms PCSDD.IReceipt.verify_rejects
#print axioms PCSDD.IReceipt.verify_rejects_changed
#print axioms PCSDD.audit_feasible_iff
#print axioms PCSDD.audit_gap
#print axioms PCSDD.audit_no_gap_unresolved
#print axioms PCSDD.audit_no_gap_infeasible
#print axioms PCSDD.audit_gap_present
#print axioms PCSDD.Controls.tAB_equivalent
#print axioms PCSDD.Controls.tOpp_inconsistent
#print axioms PCSDD.Controls.dm24_decision
#print axioms PCSDD.Controls.dm24_equivalent
#print axioms PCSDD.Controls.tDense_nothing_claimed
#print axioms PCSDD.Controls.lockBoth_infeasible
#print axioms PCSDD.Controls.choices12_summary
