import PCSOmega
import PCSOmega.Controls
import PCSDecisionDiagram
import PCSDecisionDiagram.Controls

/-! Integration audit of every original named positive theorem and computation-certificate helper. -/

#print axioms PCSDD.BOp.app_comm
#print axioms PCSDD.findNode_some
#print axioms PCSDD.findNode_none
#print axioms PCSDD.Inv.empty
#print axioms PCSDD.MemoOK.extend
#print axioms PCSDD.mkNode_spec
#print axioms PCSDD.memoLookup_mem
#print axioms PCSDD.evalD_terminal
#print axioms PCSDD.termOp_spec
#print axioms PCSDD.cof_spec
#print axioms PCSDD.topVar_lt_of_ge2
#print axioms PCSDD.apply_spec
#print axioms PCSDD.apply_ops_le
#print axioms PCSDD.apply_exhausted
#print axioms PCSDD.Inv.visits
#print axioms PCSDD.Inv.wsteps
#print axioms PCSDD.compile_spec
#print axioms PCSDD.cellRec_zero
#print axioms PCSDD.cellRec_one
#print axioms PCSDD.cellRec_node
#print axioms PCSDD.mem_candL
#print axioms PCSDD.branch_split
#print axioms PCSDD.candL_split
#print axioms PCSDD.summ_branch
#print axioms PCSDD.comb_bcell_skip
#print axioms PCSDD.summ_cellRec
#print axioms PCSDD.Denotes.extend
#print axioms PCSDD.RootsOK.extend
#print axioms PCSDD.allEval_append
#print axioms PCSDD.allEval_take
#print axioms PCSDD.conjList_spec
#print axioms PCSDD.denotes_one
#print axioms PCSDD.premLoop_spec
#print axioms PCSDD.allEval_pick_iff
#print axioms PCSDD.RootsOK.pick
#print axioms PCSDD.SatSet.mono
#print axioms PCSDD.shrink_spec
#print axioms PCSDD.coreWits_spec
#print axioms PCSDD.verify_iff
#print axioms PCSDD.check_flags
#print axioms PCSDD.check_resource_limit
#print axioms PCSDD.premAt_eq
#print axioms PCSDD.pipeline_premises
#print axioms PCSDD.check_inconsistent
#print axioms PCSDD.pipeline_decided
#print axioms PCSDD.check_equivalent
#print axioms PCSDD.check_counterexample
#print axioms PCSDD.Controls.tAB_equivalent
#print axioms PCSDD.Controls.tOpp_inconsistent
#print axioms PCSDD.Controls.dm24_decision
#print axioms PCSDD.Controls.dm24_equivalent
#print axioms PCSDD.Controls.tDense_nothing_claimed
#print axioms PCSDD.Controls.lockBoth_infeasible
#print axioms PCSDD.Controls.choices12_summary
#print axioms PCSDD.evalD_zero
#print axioms PCSDD.evalD_one
#print axioms PCSDD.getNode_idx
#print axioms PCSDD.getNode_lt
#print axioms PCSDD.getNode_none_of_ge
#print axioms PCSDD.evalD_node
#print axioms PCSDD.Valid.node
#print axioms PCSDD.topVar_le
#print axioms PCSDD.topVar_terminal
#print axioms PCSDD.topVar_node
#print axioms PCSDD.evalD_support
#print axioms PCSDD.evalD_shannon
#print axioms PCSDD.Extends.refl
#print axioms PCSDD.Extends.trans
#print axioms PCSDD.Extends.push
#print axioms PCSDD.Extends.getNode
#print axioms PCSDD.Extends.topVar
#print axioms PCSDD.evalD_extend
#print axioms PCSDD.exists_sat_unsat
#print axioms PCSDD.eq_zero_iff_unsat
#print axioms PCSDD.eq_one_iff_valid
#print axioms PCSDD.getNode_some_of_ge2
#print axioms PCSDD.children_agree
#print axioms PCSDD.children_agree_same
#print axioms PCSDD.canonical
#print axioms PCSDD.canonical'
#print axioms PCSDD.IReceipt.verify_iff
#print axioms PCSDD.IReceipt.verify_rejects
#print axioms PCSDD.IReceipt.verify_rejects_changed
#print axioms PCSDD.strictSorted_nodup
#print axioms PCSDD.validFacts
#print axioms PCSDD.check_decided
#print axioms PCSDD.feasible_iff
#print axioms PCSDD.optimal_iff
#print axioms PCSDD.guard_iff
#print axioms PCSDD.plan_valid
#print axioms PCSDD.plan_cases
#print axioms PCSDD.plan_ok
#print axioms PCSDD.plan_resource_limit
#print axioms PCSDD.plan_inconsistent
#print axioms PCSDD.plan_no_feasible
#print axioms PCSDD.plan_optimal
#print axioms PCSDD.plan_flags
#print axioms PCSDD.js_safe_bounds
#print axioms PCSDD.audit_unfold
#print axioms PCSDD.audit_feasible_iff
#print axioms PCSDD.audit_gap
#print axioms PCSDD.audit_no_gap_unresolved
#print axioms PCSDD.audit_no_gap_infeasible
#print axioms PCSDD.audit_gap_present
#print axioms PCSDD.objL_eq
#print axioms PCSDD.objL_zero
#print axioms PCSDD.testBit_maskL
#print axioms PCSDD.maskL_zero_testBit
#print axioms PCSDD.locksB_iff
#print axioms PCSDD.feasL_zero_iff
#print axioms PCSDD.mem_candL_zero
#print axioms PCSDD.summ_root
#print axioms PCSDD.bellman_correct
#print axioms PCSDD.objective_le
#print axioms PCSDD.bellman_bounds
#print axioms PCSDD.winnersCell_two
#print axioms PCSDD.inspect_eq
#print axioms PCSDD.stepCell_eq
#print axioms PCSDD.passUpTo_inv
#print axioms PCSDD.bellmanPass_spec
#print axioms PCSDD.choiceRec_node
#print axioms PCSDD.chosen_child_some
#print axioms PCSDD.walkPy_level
#print axioms PCSDD.walkPy_spec
#print axioms PCSDD.summ_min
#print axioms PCSDD.summ_none
#print axioms PCSDD.optC_cons
#print axioms PCSDD.optC_skip_iff
#print axioms PCSDD.comb_cost_le
#print axioms PCSDD.comb_lt
#print axioms PCSDD.bcell_some
#print axioms PCSDD.recon_least
#print axioms PCSDD.recon_spec
#print axioms PCSDD.Summ.nil
#print axioms PCSDD.Summ.single
#print axioms PCSDD.Summ.unique
#print axioms PCSDD.noneIff_of_some
#print axioms PCSDD.Summ.append_lt
#print axioms PCSDD.Summ.perm_append
#print axioms PCSDD.Summ.append
#print axioms PCSDD.Summ.shift
#print axioms PCSDD.shiftCell_zero
#print axioms PCSDD.shiftP_zero
#print axioms PCSDD.comb_shift_pos
#print axioms PCSDD.validB_iff
#print axioms PCSDD.bellmanChecked_ok
#print axioms PCSDD.envL_zero
#print axioms PCSDD.envL_cons_self
#print axioms PCSDD.envL_cons_succ
#print axioms PCSDD.evalD_skip
#print axioms PCSDD.evalD_level_node
#print axioms PCSDD.terminal_of_topVar
#print axioms PCSDD.wit_eq
#print axioms PCSDD.wit_length
#print axioms PCSDD.wit_least
#print axioms PCSDD.satL_zero_iff
#print axioms PCSDD.world_spec
#print axioms PCSDD.witSteps_eq
#print axioms PCSDD.witSteps_le
#print axioms PCSOmega.disagree_iff
#print axioms PCSOmega.semEquiv_iff_lists
#print axioms PCSOmega.check_none_iff
#print axioms PCSOmega.check_some_sound
#print axioms PCSOmega.check_some_least
#print axioms PCSOmega.checkReceipt_equivalent_iff
#print axioms PCSOmega.checkReceipt_count
#print axioms PCSOmega.checkReceipt_flags
#print axioms PCSOmega.verifyCheckReceipt_iff
#print axioms PCSOmega.screen_some_not_equiv
#print axioms PCSOmega.screen_append_of_some
#print axioms PCSOmega.screen_isSome_append_left
#print axioms PCSOmega.screen_none_of_equiv
#print axioms PCSOmega.Controls.implication_reversal_not_equiv
#print axioms PCSOmega.Controls.de_morgan_equiv
#print axioms PCSOmega.Controls.remembered_rejection
#print axioms PCSOmega.Controls.screen_survivor_not_equiv
#print axioms PCSOmega.Controls.episode_solution_sound
#print axioms PCSOmega.BForm.eval_iff_holds
#print axioms PCSOmega.BForm.eval_congr
#print axioms PCSOmega.listOf_length
#print axioms PCSOmega.envOf_listOf
#print axioms PCSOmega.allAsg_zero
#print axioms PCSOmega.mem_allAsg
#print axioms PCSOmega.length_allAsg
#print axioms PCSOmega.nodup_allAsg
#print axioms PCSOmega.lexLt_irrefl
#print axioms PCSOmega.lexLt_trans
#print axioms PCSOmega.lexLt_total
#print axioms PCSOmega.pairwise_lexLt_allAsg
#print axioms PCSOmega.IsLexLeast.unique
#print axioms PCSOmega.find?_pairwise_least
#print axioms PCSOmega.isLexLeast_cons_false
#print axioms PCSOmega.isLexLeast_cons_true
#print axioms PCSOmega.strictSortedS_head_lt
#print axioms PCSOmega.strictSortedS_nodup
#print axioms PCSOmega.lower_eval
#print axioms PCSOmega.idxOf?_isSome_iff
#print axioms PCSOmega.idxOf?_lt
#print axioms PCSOmega.lower_isSome_iff
#print axioms PCSOmega.lower_size_depth
#print axioms PCSOmega.applyAction_bounded
#print axioms PCSOmega.actionsAux_length
#print axioms PCSOmega.actionsOf_length
#print axioms PCSOmega.screenWork_fst
#print axioms PCSOmega.screenWork_snd_le
#print axioms PCSOmega.expand_solution
#print axioms PCSOmega.remember_solution
#print axioms PCSOmega.examine_solInv
#print axioms PCSOmega.loop_solInv
#print axioms PCSOmega.initState_solInv
#print axioms PCSOmega.search_solution_sound
#print axioms PCSOmega.search_status_iff
#print axioms PCSOmega.search_flags
#print axioms PCSOmega.expand_fields
#print axioms PCSOmega.recordAttempt_fields
#print axioms PCSOmega.remember_fields
#print axioms PCSOmega.examine_accInv
#print axioms PCSOmega.loop_accInv
#print axioms PCSOmega.initState_accInv
#print axioms PCSOmega.search_accounting
#print axioms PCSOmega.search_checksUsed_eq
#print axioms PCSOmega.finishChecked_sol
#print axioms PCSOmega.finishChecked_sol'
#print axioms PCSOmega.replayRow_inv
#print axioms PCSOmega.replayRows_inv
#print axioms PCSOmega.replay_sound

-- Proof portability helpers; these are not additional benchmark problems.
#print axioms PCSDD.apply_ok_add_fuel
#print axioms PCSDD.apply_ok_target
#print axioms PCSDD.CompileCertificate.sound
#print axioms PCSDD.pipeline_from_certificates
#print axioms PCSDD.equivalent_from_certificates
#print axioms PCSDD.check_of_pipeline
#print axioms PCSDD.plan_of_check
#print axioms PCSDD.plan_from_pipeline
#print axioms PCSDD.counterexample_from_pipeline
#print axioms PCSDD.ApplyCertificate.sound
#print axioms StagedControl.c5
#print axioms StagedControl.c7
#print axioms StagedControl.c8
#print axioms StagedControl.c6
#print axioms StagedControl.c4
#print axioms StagedControl.c10
#print axioms StagedControl.c12
#print axioms StagedControl.c13
#print axioms StagedControl.c11
#print axioms StagedControl.c9
#print axioms StagedControl.c3
#print axioms StagedControl.c16
#print axioms StagedControl.c18
#print axioms StagedControl.c19
#print axioms StagedControl.c17
#print axioms StagedControl.c15
#print axioms StagedControl.c21
#print axioms StagedControl.c23
#print axioms StagedControl.c24
#print axioms StagedControl.c22
#print axioms StagedControl.c20
#print axioms StagedControl.c14
#print axioms StagedControl.c2
#print axioms StagedControl.c28
#print axioms StagedControl.c30
#print axioms StagedControl.c31
#print axioms StagedControl.c29
#print axioms StagedControl.c27
#print axioms StagedControl.c33
#print axioms StagedControl.c35
#print axioms StagedControl.c36
#print axioms StagedControl.c34
#print axioms StagedControl.c32
#print axioms StagedControl.c26
#print axioms StagedControl.c39
#print axioms StagedControl.c41
#print axioms StagedControl.c42
#print axioms StagedControl.c40
#print axioms StagedControl.c38
#print axioms StagedControl.c44
#print axioms StagedControl.c46
#print axioms StagedControl.c47
#print axioms StagedControl.c45
#print axioms StagedControl.c43
#print axioms StagedControl.c37
#print axioms StagedControl.c25
#print axioms StagedControl.c1
#print axioms StagedControl.c0
#print axioms StagedControl.c53
#print axioms StagedControl.c52
#print axioms StagedControl.c56
#print axioms StagedControl.c55
#print axioms StagedControl.c58
#print axioms StagedControl.c57
#print axioms StagedControl.c54
#print axioms StagedControl.c51
#print axioms StagedControl.c61
#print axioms StagedControl.c60
#print axioms StagedControl.c64
#print axioms StagedControl.c63
#print axioms StagedControl.c66
#print axioms StagedControl.c65
#print axioms StagedControl.c62
#print axioms StagedControl.c59
#print axioms StagedControl.c50
#print axioms StagedControl.c70
#print axioms StagedControl.c69
#print axioms StagedControl.c73
#print axioms StagedControl.c72
#print axioms StagedControl.c75
#print axioms StagedControl.c74
#print axioms StagedControl.c71
#print axioms StagedControl.c68
#print axioms StagedControl.c78
#print axioms StagedControl.c77
#print axioms StagedControl.c81
#print axioms StagedControl.c80
#print axioms StagedControl.c83
#print axioms StagedControl.c82
#print axioms StagedControl.c79
#print axioms StagedControl.c76
#print axioms StagedControl.c67
#print axioms StagedControl.c49
#print axioms StagedControl.c88
#print axioms StagedControl.c87
#print axioms StagedControl.c91
#print axioms StagedControl.c90
#print axioms StagedControl.c93
#print axioms StagedControl.c92
#print axioms StagedControl.c89
#print axioms StagedControl.c86
#print axioms StagedControl.c96
#print axioms StagedControl.c95
#print axioms StagedControl.c99
#print axioms StagedControl.c98
#print axioms StagedControl.c101
#print axioms StagedControl.c100
#print axioms StagedControl.c97
#print axioms StagedControl.c94
#print axioms StagedControl.c85
#print axioms StagedControl.c105
#print axioms StagedControl.c104
#print axioms StagedControl.c108
#print axioms StagedControl.c107
#print axioms StagedControl.c110
#print axioms StagedControl.c109
#print axioms StagedControl.c106
#print axioms StagedControl.c103
#print axioms StagedControl.c113
#print axioms StagedControl.c112
#print axioms StagedControl.c116
#print axioms StagedControl.c115
#print axioms StagedControl.c118
#print axioms StagedControl.c117
#print axioms StagedControl.c114
#print axioms StagedControl.c111
#print axioms StagedControl.c102
#print axioms StagedControl.c84
#print axioms StagedControl.c48
#print axioms StagedControl.hx
#print axioms StagedControl.ha
#print axioms StagedControl.pipe
#print axioms StagedControl.result
#print axioms StagedChoices.c4
#print axioms StagedChoices.c5
#print axioms StagedChoices.c3
#print axioms StagedChoices.c8
#print axioms StagedChoices.c9
#print axioms StagedChoices.c7
#print axioms StagedChoices.c11
#print axioms StagedChoices.c12
#print axioms StagedChoices.c10
#print axioms StagedChoices.c6
#print axioms StagedChoices.c2
#print axioms StagedChoices.c15
#print axioms StagedChoices.c16
#print axioms StagedChoices.c14
#print axioms StagedChoices.c19
#print axioms StagedChoices.c20
#print axioms StagedChoices.c18
#print axioms StagedChoices.c22
#print axioms StagedChoices.c23
#print axioms StagedChoices.c21
#print axioms StagedChoices.c17
#print axioms StagedChoices.c13
#print axioms StagedChoices.c1
#print axioms StagedChoices.c27
#print axioms StagedChoices.c28
#print axioms StagedChoices.c26
#print axioms StagedChoices.c31
#print axioms StagedChoices.c32
#print axioms StagedChoices.c30
#print axioms StagedChoices.c34
#print axioms StagedChoices.c35
#print axioms StagedChoices.c33
#print axioms StagedChoices.c29
#print axioms StagedChoices.c25
#print axioms StagedChoices.c38
#print axioms StagedChoices.c39
#print axioms StagedChoices.c37
#print axioms StagedChoices.c42
#print axioms StagedChoices.c43
#print axioms StagedChoices.c41
#print axioms StagedChoices.c45
#print axioms StagedChoices.c46
#print axioms StagedChoices.c44
#print axioms StagedChoices.c40
#print axioms StagedChoices.c36
#print axioms StagedChoices.c24
#print axioms StagedChoices.c0
#print axioms StagedChoices.c47
#print axioms StagedChoices.hx
#print axioms StagedChoices.ha
#print axioms StagedChoices.pipe
#print axioms StagedChoices.result
#print axioms StagedDense.c3
#print axioms StagedDense.c4
#print axioms StagedDense.a7
#print axioms StagedDense.a8
#print axioms StagedDense.a6
#print axioms StagedDense.a10
#print axioms StagedDense.a11
#print axioms StagedDense.a9
#print axioms StagedDense.a5
#print axioms StagedDense.c2
#print axioms StagedDense.c14
#print axioms StagedDense.c15
#print axioms StagedDense.a18
#print axioms StagedDense.a19
#print axioms StagedDense.a17
#print axioms StagedDense.a21
#print axioms StagedDense.a22
#print axioms StagedDense.a20
#print axioms StagedDense.a16
#print axioms StagedDense.c13
#print axioms StagedDense.c24
#print axioms StagedDense.c25
#print axioms StagedDense.a28
#print axioms StagedDense.a29
#print axioms StagedDense.a27
#print axioms StagedDense.a31
#print axioms StagedDense.a32
#print axioms StagedDense.a30
#print axioms StagedDense.a26
#print axioms StagedDense.c23
#print axioms StagedDense.a35
#print axioms StagedDense.a37
#print axioms StagedDense.a38
#print axioms StagedDense.a36
#print axioms StagedDense.a34
#print axioms StagedDense.a41
#print axioms StagedDense.a42
#print axioms StagedDense.a40
#print axioms StagedDense.a44
#print axioms StagedDense.a46
#print axioms StagedDense.a47
#print axioms StagedDense.a45
#print axioms StagedDense.a43
#print axioms StagedDense.a39
#print axioms StagedDense.a33
#print axioms StagedDense.c12
#print axioms StagedDense.a50
#print axioms StagedDense.a52
#print axioms StagedDense.a54
#print axioms StagedDense.a55
#print axioms StagedDense.a53
#print axioms StagedDense.a51
#print axioms StagedDense.a49
#print axioms StagedDense.a59
#print axioms StagedDense.a60
#print axioms StagedDense.a58
#print axioms StagedDense.a62
#print axioms StagedDense.a63
#print axioms StagedDense.a61
#print axioms StagedDense.a57
#print axioms StagedDense.a66
#print axioms StagedDense.a68
#print axioms StagedDense.a69
#print axioms StagedDense.a67
#print axioms StagedDense.a65
#print axioms StagedDense.a71
#print axioms StagedDense.a73
#print axioms StagedDense.a74
#print axioms StagedDense.a72
#print axioms StagedDense.a70
#print axioms StagedDense.a64
#print axioms StagedDense.a56
#print axioms StagedDense.a48
#print axioms StagedDense.c1
#print axioms StagedDense.c77
#print axioms StagedDense.c78
#print axioms StagedDense.a81
#print axioms StagedDense.a82
#print axioms StagedDense.a80
#print axioms StagedDense.a84
#print axioms StagedDense.a85
#print axioms StagedDense.a83
#print axioms StagedDense.a79
#print axioms StagedDense.c76
#print axioms StagedDense.c88
#print axioms StagedDense.c89
#print axioms StagedDense.a92
#print axioms StagedDense.a93
#print axioms StagedDense.a91
#print axioms StagedDense.a95
#print axioms StagedDense.a96
#print axioms StagedDense.a94
#print axioms StagedDense.a90
#print axioms StagedDense.c87
#print axioms StagedDense.c98
#print axioms StagedDense.c99
#print axioms StagedDense.a102
#print axioms StagedDense.a103
#print axioms StagedDense.a101
#print axioms StagedDense.a105
#print axioms StagedDense.a106
#print axioms StagedDense.a104
#print axioms StagedDense.a100
#print axioms StagedDense.c97
#print axioms StagedDense.a109
#print axioms StagedDense.a111
#print axioms StagedDense.a112
#print axioms StagedDense.a110
#print axioms StagedDense.a108
#print axioms StagedDense.a115
#print axioms StagedDense.a116
#print axioms StagedDense.a114
#print axioms StagedDense.a118
#print axioms StagedDense.a120
#print axioms StagedDense.a121
#print axioms StagedDense.a119
#print axioms StagedDense.a117
#print axioms StagedDense.a113
#print axioms StagedDense.a107
#print axioms StagedDense.c86
#print axioms StagedDense.a124
#print axioms StagedDense.a126
#print axioms StagedDense.a128
#print axioms StagedDense.a129
#print axioms StagedDense.a127
#print axioms StagedDense.a125
#print axioms StagedDense.a123
#print axioms StagedDense.a133
#print axioms StagedDense.a134
#print axioms StagedDense.a132
#print axioms StagedDense.a136
#print axioms StagedDense.a137
#print axioms StagedDense.a135
#print axioms StagedDense.a131
#print axioms StagedDense.a140
#print axioms StagedDense.a142
#print axioms StagedDense.a143
#print axioms StagedDense.a141
#print axioms StagedDense.a139
#print axioms StagedDense.a145
#print axioms StagedDense.a147
#print axioms StagedDense.a148
#print axioms StagedDense.a146
#print axioms StagedDense.a144
#print axioms StagedDense.a138
#print axioms StagedDense.a130
#print axioms StagedDense.a122
#print axioms StagedDense.c75
#print axioms StagedDense.a153
#print axioms StagedDense.a156
#print axioms StagedDense.a158
#print axioms StagedDense.a159
#print axioms StagedDense.a157
#print axioms StagedDense.a155
#print axioms StagedDense.a162
#print axioms StagedDense.a163
#print axioms StagedDense.a161
#print axioms StagedDense.a165
#print axioms StagedDense.a166
#print axioms StagedDense.a164
#print axioms StagedDense.a160
#print axioms StagedDense.a154
#print axioms StagedDense.a152
#print axioms StagedDense.a170
#print axioms StagedDense.a172
#print axioms StagedDense.a173
#print axioms StagedDense.a171
#print axioms StagedDense.a169
#print axioms StagedDense.a176
#print axioms StagedDense.a177
#print axioms StagedDense.a175
#print axioms StagedDense.a179
#print axioms StagedDense.a180
#print axioms StagedDense.a178
#print axioms StagedDense.a174
#print axioms StagedDense.a168
#print axioms StagedDense.a184
#print axioms StagedDense.a186
#print axioms StagedDense.a187
#print axioms StagedDense.a185
#print axioms StagedDense.a183
#print axioms StagedDense.a189
#print axioms StagedDense.a191
#print axioms StagedDense.a192
#print axioms StagedDense.a190
#print axioms StagedDense.a188
#print axioms StagedDense.a182
#print axioms StagedDense.a195
#print axioms StagedDense.a197
#print axioms StagedDense.a198
#print axioms StagedDense.a196
#print axioms StagedDense.a194
#print axioms StagedDense.a200
#print axioms StagedDense.a202
#print axioms StagedDense.a203
#print axioms StagedDense.a201
#print axioms StagedDense.a199
#print axioms StagedDense.a193
#print axioms StagedDense.a181
#print axioms StagedDense.a167
#print axioms StagedDense.a151
#print axioms StagedDense.a208
#print axioms StagedDense.a210
#print axioms StagedDense.a211
#print axioms StagedDense.a209
#print axioms StagedDense.a207
#print axioms StagedDense.a214
#print axioms StagedDense.a215
#print axioms StagedDense.a213
#print axioms StagedDense.a217
#print axioms StagedDense.a218
#print axioms StagedDense.a216
#print axioms StagedDense.a212
#print axioms StagedDense.a206
#print axioms StagedDense.a222
#print axioms StagedDense.a223
#print axioms StagedDense.a221
#print axioms StagedDense.a225
#print axioms StagedDense.a226
#print axioms StagedDense.a224
#print axioms StagedDense.a220
#print axioms StagedDense.a229
#print axioms StagedDense.a230
#print axioms StagedDense.a228
#print axioms StagedDense.a232
#print axioms StagedDense.a233
#print axioms StagedDense.a231
#print axioms StagedDense.a227
#print axioms StagedDense.a219
#print axioms StagedDense.a205
#print axioms StagedDense.a237
#print axioms StagedDense.a239
#print axioms StagedDense.a240
#print axioms StagedDense.a238
#print axioms StagedDense.a236
#print axioms StagedDense.a243
#print axioms StagedDense.a244
#print axioms StagedDense.a242
#print axioms StagedDense.a246
#print axioms StagedDense.a247
#print axioms StagedDense.a245
#print axioms StagedDense.a241
#print axioms StagedDense.a235
#print axioms StagedDense.a251
#print axioms StagedDense.a252
#print axioms StagedDense.a250
#print axioms StagedDense.a254
#print axioms StagedDense.a255
#print axioms StagedDense.a253
#print axioms StagedDense.a249
#print axioms StagedDense.a258
#print axioms StagedDense.a259
#print axioms StagedDense.a257
#print axioms StagedDense.a261
#print axioms StagedDense.a262
#print axioms StagedDense.a260
#print axioms StagedDense.a256
#print axioms StagedDense.a248
#print axioms StagedDense.a234
#print axioms StagedDense.a204
#print axioms StagedDense.a150
#print axioms StagedDense.a268
#print axioms StagedDense.a270
#print axioms StagedDense.a271
#print axioms StagedDense.a269
#print axioms StagedDense.a267
#print axioms StagedDense.a274
#print axioms StagedDense.a275
#print axioms StagedDense.a273
#print axioms StagedDense.a277
#print axioms StagedDense.a278
#print axioms StagedDense.a276
#print axioms StagedDense.a272
#print axioms StagedDense.a266
#print axioms StagedDense.a282
#print axioms StagedDense.a283
#print axioms StagedDense.a281
#print axioms StagedDense.a285
#print axioms StagedDense.a286
#print axioms StagedDense.a284
#print axioms StagedDense.a280
#print axioms StagedDense.a289
#print axioms StagedDense.a290
#print axioms StagedDense.a288
#print axioms StagedDense.a292
#print axioms StagedDense.a293
#print axioms StagedDense.a291
#print axioms StagedDense.a287
#print axioms StagedDense.a279
#print axioms StagedDense.a265
#print axioms StagedDense.a298
#print axioms StagedDense.a299
#print axioms StagedDense.a297
#print axioms StagedDense.a301
#print axioms StagedDense.a302
#print axioms StagedDense.a300
#print axioms StagedDense.a296
#print axioms StagedDense.a305
#print axioms StagedDense.a306
#print axioms StagedDense.a304
#print axioms StagedDense.a308
#print axioms StagedDense.a309
#print axioms StagedDense.a307
#print axioms StagedDense.a303
#print axioms StagedDense.a295
#print axioms StagedDense.a313
#print axioms StagedDense.a314
#print axioms StagedDense.a312
#print axioms StagedDense.a316
#print axioms StagedDense.a317
#print axioms StagedDense.a315
#print axioms StagedDense.a311
#print axioms StagedDense.a320
#print axioms StagedDense.a321
#print axioms StagedDense.a319
#print axioms StagedDense.a323
#print axioms StagedDense.a324
#print axioms StagedDense.a322
#print axioms StagedDense.a318
#print axioms StagedDense.a310
#print axioms StagedDense.a294
#print axioms StagedDense.a264
#print axioms StagedDense.a330
#print axioms StagedDense.a331
#print axioms StagedDense.a329
#print axioms StagedDense.a333
#print axioms StagedDense.a334
#print axioms StagedDense.a332
#print axioms StagedDense.a328
#print axioms StagedDense.a337
#print axioms StagedDense.a338
#print axioms StagedDense.a336
#print axioms StagedDense.a340
#print axioms StagedDense.a341
#print axioms StagedDense.a339
#print axioms StagedDense.a335
#print axioms StagedDense.a327
#print axioms StagedDense.a345
#print axioms StagedDense.a346
#print axioms StagedDense.a344
#print axioms StagedDense.a348
#print axioms StagedDense.a349
#print axioms StagedDense.a347
#print axioms StagedDense.a343
#print axioms StagedDense.a352
#print axioms StagedDense.a353
#print axioms StagedDense.a351
#print axioms StagedDense.a355
#print axioms StagedDense.a356
#print axioms StagedDense.a354
#print axioms StagedDense.a350
#print axioms StagedDense.a342
#print axioms StagedDense.a326
#print axioms StagedDense.a361
#print axioms StagedDense.a362
#print axioms StagedDense.a360
#print axioms StagedDense.a364
#print axioms StagedDense.a365
#print axioms StagedDense.a363
#print axioms StagedDense.a359
#print axioms StagedDense.a368
#print axioms StagedDense.a369
#print axioms StagedDense.a367
#print axioms StagedDense.a371
#print axioms StagedDense.a372
#print axioms StagedDense.a370
#print axioms StagedDense.a366
#print axioms StagedDense.a358
#print axioms StagedDense.a376
#print axioms StagedDense.a377
#print axioms StagedDense.a375
#print axioms StagedDense.a379
#print axioms StagedDense.a380
#print axioms StagedDense.a378
#print axioms StagedDense.a374
#print axioms StagedDense.a383
#print axioms StagedDense.a384
#print axioms StagedDense.a382
#print axioms StagedDense.a386
#print axioms StagedDense.a387
#print axioms StagedDense.a385
#print axioms StagedDense.a381
#print axioms StagedDense.a373
#print axioms StagedDense.a357
#print axioms StagedDense.a325
#print axioms StagedDense.a263
#print axioms StagedDense.a149
#print axioms StagedDense.c0
#print axioms StagedDense.c388
#print axioms StagedDense.a395
#print axioms StagedDense.a397
#print axioms StagedDense.a398
#print axioms StagedDense.a396
#print axioms StagedDense.a394
#print axioms StagedDense.a401
#print axioms StagedDense.a402
#print axioms StagedDense.a400
#print axioms StagedDense.a404
#print axioms StagedDense.a405
#print axioms StagedDense.a403
#print axioms StagedDense.a399
#print axioms StagedDense.a393
#print axioms StagedDense.a409
#print axioms StagedDense.a410
#print axioms StagedDense.a408
#print axioms StagedDense.a412
#print axioms StagedDense.a413
#print axioms StagedDense.a411
#print axioms StagedDense.a407
#print axioms StagedDense.a416
#print axioms StagedDense.a417
#print axioms StagedDense.a415
#print axioms StagedDense.a419
#print axioms StagedDense.a420
#print axioms StagedDense.a418
#print axioms StagedDense.a414
#print axioms StagedDense.a406
#print axioms StagedDense.a392
#print axioms StagedDense.a425
#print axioms StagedDense.a426
#print axioms StagedDense.a424
#print axioms StagedDense.a428
#print axioms StagedDense.a429
#print axioms StagedDense.a427
#print axioms StagedDense.a423
#print axioms StagedDense.a432
#print axioms StagedDense.a433
#print axioms StagedDense.a431
#print axioms StagedDense.a435
#print axioms StagedDense.a436
#print axioms StagedDense.a434
#print axioms StagedDense.a430
#print axioms StagedDense.a422
#print axioms StagedDense.a440
#print axioms StagedDense.a441
#print axioms StagedDense.a439
#print axioms StagedDense.a443
#print axioms StagedDense.a444
#print axioms StagedDense.a442
#print axioms StagedDense.a438
#print axioms StagedDense.a447
#print axioms StagedDense.a448
#print axioms StagedDense.a446
#print axioms StagedDense.a450
#print axioms StagedDense.a451
#print axioms StagedDense.a449
#print axioms StagedDense.a445
#print axioms StagedDense.a437
#print axioms StagedDense.a421
#print axioms StagedDense.a391
#print axioms StagedDense.a457
#print axioms StagedDense.a458
#print axioms StagedDense.a456
#print axioms StagedDense.a460
#print axioms StagedDense.a461
#print axioms StagedDense.a459
#print axioms StagedDense.a455
#print axioms StagedDense.a464
#print axioms StagedDense.a465
#print axioms StagedDense.a463
#print axioms StagedDense.a467
#print axioms StagedDense.a468
#print axioms StagedDense.a466
#print axioms StagedDense.a462
#print axioms StagedDense.a454
#print axioms StagedDense.a472
#print axioms StagedDense.a473
#print axioms StagedDense.a471
#print axioms StagedDense.a475
#print axioms StagedDense.a476
#print axioms StagedDense.a474
#print axioms StagedDense.a470
#print axioms StagedDense.a479
#print axioms StagedDense.a480
#print axioms StagedDense.a478
#print axioms StagedDense.a482
#print axioms StagedDense.a483
#print axioms StagedDense.a481
#print axioms StagedDense.a477
#print axioms StagedDense.a469
#print axioms StagedDense.a453
#print axioms StagedDense.a488
#print axioms StagedDense.a489
#print axioms StagedDense.a487
#print axioms StagedDense.a491
#print axioms StagedDense.a492
#print axioms StagedDense.a490
#print axioms StagedDense.a486
#print axioms StagedDense.a495
#print axioms StagedDense.a496
#print axioms StagedDense.a494
#print axioms StagedDense.a498
#print axioms StagedDense.a499
#print axioms StagedDense.a497
#print axioms StagedDense.a493
#print axioms StagedDense.a485
#print axioms StagedDense.a503
#print axioms StagedDense.a504
#print axioms StagedDense.a502
#print axioms StagedDense.a506
#print axioms StagedDense.a507
#print axioms StagedDense.a505
#print axioms StagedDense.a501
#print axioms StagedDense.a510
#print axioms StagedDense.a511
#print axioms StagedDense.a509
#print axioms StagedDense.a513
#print axioms StagedDense.a514
#print axioms StagedDense.a512
#print axioms StagedDense.a508
#print axioms StagedDense.a500
#print axioms StagedDense.a484
#print axioms StagedDense.a452
#print axioms StagedDense.a390
#print axioms StagedDense.a521
#print axioms StagedDense.a522
#print axioms StagedDense.a520
#print axioms StagedDense.a524
#print axioms StagedDense.a525
#print axioms StagedDense.a523
#print axioms StagedDense.a519
#print axioms StagedDense.a528
#print axioms StagedDense.a529
#print axioms StagedDense.a527
#print axioms StagedDense.a531
#print axioms StagedDense.a532
#print axioms StagedDense.a530
#print axioms StagedDense.a526
#print axioms StagedDense.a518
#print axioms StagedDense.a536
#print axioms StagedDense.a537
#print axioms StagedDense.a535
#print axioms StagedDense.a539
#print axioms StagedDense.a540
#print axioms StagedDense.a538
#print axioms StagedDense.a534
#print axioms StagedDense.a543
#print axioms StagedDense.a544
#print axioms StagedDense.a542
#print axioms StagedDense.a546
#print axioms StagedDense.a547
#print axioms StagedDense.a545
#print axioms StagedDense.a541
#print axioms StagedDense.a533
#print axioms StagedDense.a517
#print axioms StagedDense.a552
#print axioms StagedDense.a553
#print axioms StagedDense.a551
#print axioms StagedDense.a555
#print axioms StagedDense.a556
#print axioms StagedDense.a554
#print axioms StagedDense.a550
#print axioms StagedDense.a559
#print axioms StagedDense.a560
#print axioms StagedDense.a558
#print axioms StagedDense.a562
#print axioms StagedDense.a563
#print axioms StagedDense.a561
#print axioms StagedDense.a557
#print axioms StagedDense.a549
#print axioms StagedDense.a567
#print axioms StagedDense.a568
#print axioms StagedDense.a566
#print axioms StagedDense.a570
#print axioms StagedDense.a571
#print axioms StagedDense.a569
#print axioms StagedDense.a565
#print axioms StagedDense.a574
#print axioms StagedDense.a575
#print axioms StagedDense.a573
#print axioms StagedDense.a577
#print axioms StagedDense.a578
#print axioms StagedDense.a576
#print axioms StagedDense.a572
#print axioms StagedDense.a564
#print axioms StagedDense.a548
#print axioms StagedDense.a516
#print axioms StagedDense.a584
#print axioms StagedDense.a585
#print axioms StagedDense.a583
#print axioms StagedDense.a587
#print axioms StagedDense.a588
#print axioms StagedDense.a586
#print axioms StagedDense.a582
#print axioms StagedDense.a591
#print axioms StagedDense.a592
#print axioms StagedDense.a590
#print axioms StagedDense.a594
#print axioms StagedDense.a595
#print axioms StagedDense.a593
#print axioms StagedDense.a589
#print axioms StagedDense.a581
#print axioms StagedDense.a599
#print axioms StagedDense.a600
#print axioms StagedDense.a598
#print axioms StagedDense.a602
#print axioms StagedDense.a603
#print axioms StagedDense.a601
#print axioms StagedDense.a597
#print axioms StagedDense.a606
#print axioms StagedDense.a607
#print axioms StagedDense.a605
#print axioms StagedDense.a609
#print axioms StagedDense.a610
#print axioms StagedDense.a608
#print axioms StagedDense.a604
#print axioms StagedDense.a596
#print axioms StagedDense.a580
#print axioms StagedDense.a615
#print axioms StagedDense.a616
#print axioms StagedDense.a614
#print axioms StagedDense.a618
#print axioms StagedDense.a619
#print axioms StagedDense.a617
#print axioms StagedDense.a613
#print axioms StagedDense.a622
#print axioms StagedDense.a623
#print axioms StagedDense.a621
#print axioms StagedDense.a625
#print axioms StagedDense.a626
#print axioms StagedDense.a624
#print axioms StagedDense.a620
#print axioms StagedDense.a612
#print axioms StagedDense.a630
#print axioms StagedDense.a631
#print axioms StagedDense.a629
#print axioms StagedDense.a633
#print axioms StagedDense.a634
#print axioms StagedDense.a632
#print axioms StagedDense.a628
#print axioms StagedDense.a637
#print axioms StagedDense.a638
#print axioms StagedDense.a636
#print axioms StagedDense.a640
#print axioms StagedDense.a641
#print axioms StagedDense.a639
#print axioms StagedDense.a635
#print axioms StagedDense.a627
#print axioms StagedDense.a611
#print axioms StagedDense.a579
#print axioms StagedDense.a515
#print axioms StagedDense.a389
#print axioms StagedDense.a648
#print axioms StagedDense.a649
#print axioms StagedDense.a647
#print axioms StagedDense.a651
#print axioms StagedDense.a653
#print axioms StagedDense.a654
#print axioms StagedDense.a652
#print axioms StagedDense.a650
#print axioms StagedDense.a646
#print axioms StagedDense.a657
#print axioms StagedDense.a659
#print axioms StagedDense.a660
#print axioms StagedDense.a658
#print axioms StagedDense.a656
#print axioms StagedDense.a663
#print axioms StagedDense.a664
#print axioms StagedDense.a662
#print axioms StagedDense.a666
#print axioms StagedDense.a667
#print axioms StagedDense.a665
#print axioms StagedDense.a661
#print axioms StagedDense.a655
#print axioms StagedDense.a645
#print axioms StagedDense.a671
#print axioms StagedDense.a673
#print axioms StagedDense.a674
#print axioms StagedDense.a672
#print axioms StagedDense.a670
#print axioms StagedDense.a677
#print axioms StagedDense.a678
#print axioms StagedDense.a676
#print axioms StagedDense.a680
#print axioms StagedDense.a681
#print axioms StagedDense.a679
#print axioms StagedDense.a675
#print axioms StagedDense.a669
#print axioms StagedDense.a685
#print axioms StagedDense.a686
#print axioms StagedDense.a684
#print axioms StagedDense.a688
#print axioms StagedDense.a689
#print axioms StagedDense.a687
#print axioms StagedDense.a683
#print axioms StagedDense.a692
#print axioms StagedDense.a693
#print axioms StagedDense.a691
#print axioms StagedDense.a695
#print axioms StagedDense.a696
#print axioms StagedDense.a694
#print axioms StagedDense.a690
#print axioms StagedDense.a682
#print axioms StagedDense.a668
#print axioms StagedDense.a644
#print axioms StagedDense.a701
#print axioms StagedDense.a703
#print axioms StagedDense.a704
#print axioms StagedDense.a702
#print axioms StagedDense.a700
#print axioms StagedDense.a707
#print axioms StagedDense.a708
#print axioms StagedDense.a706
#print axioms StagedDense.a710
#print axioms StagedDense.a711
#print axioms StagedDense.a709
#print axioms StagedDense.a705
#print axioms StagedDense.a699
#print axioms StagedDense.a715
#print axioms StagedDense.a716
#print axioms StagedDense.a714
#print axioms StagedDense.a718
#print axioms StagedDense.a719
#print axioms StagedDense.a717
#print axioms StagedDense.a713
#print axioms StagedDense.a722
#print axioms StagedDense.a723
#print axioms StagedDense.a721
#print axioms StagedDense.a725
#print axioms StagedDense.a726
#print axioms StagedDense.a724
#print axioms StagedDense.a720
#print axioms StagedDense.a712
#print axioms StagedDense.a698
#print axioms StagedDense.a731
#print axioms StagedDense.a732
#print axioms StagedDense.a730
#print axioms StagedDense.a734
#print axioms StagedDense.a735
#print axioms StagedDense.a733
#print axioms StagedDense.a729
#print axioms StagedDense.a738
#print axioms StagedDense.a739
#print axioms StagedDense.a737
#print axioms StagedDense.a741
#print axioms StagedDense.a742
#print axioms StagedDense.a740
#print axioms StagedDense.a736
#print axioms StagedDense.a728
#print axioms StagedDense.a746
#print axioms StagedDense.a747
#print axioms StagedDense.a745
#print axioms StagedDense.a749
#print axioms StagedDense.a750
#print axioms StagedDense.a748
#print axioms StagedDense.a744
#print axioms StagedDense.a753
#print axioms StagedDense.a754
#print axioms StagedDense.a752
#print axioms StagedDense.a756
#print axioms StagedDense.a757
#print axioms StagedDense.a755
#print axioms StagedDense.a751
#print axioms StagedDense.a743
#print axioms StagedDense.a727
#print axioms StagedDense.a697
#print axioms StagedDense.a643
#print axioms StagedDense.a763
#print axioms StagedDense.a765
#print axioms StagedDense.a766
#print axioms StagedDense.a764
#print axioms StagedDense.a762
#print axioms StagedDense.a769
#print axioms StagedDense.a770
#print axioms StagedDense.a768
#print axioms StagedDense.a772
#print axioms StagedDense.a773
#print axioms StagedDense.a771
#print axioms StagedDense.a767
#print axioms StagedDense.a761
#print axioms StagedDense.a777
#print axioms StagedDense.a778
#print axioms StagedDense.a776
#print axioms StagedDense.a780
#print axioms StagedDense.a781
#print axioms StagedDense.a779
#print axioms StagedDense.a775
#print axioms StagedDense.a784
#print axioms StagedDense.a785
#print axioms StagedDense.a783
#print axioms StagedDense.a787
#print axioms StagedDense.a788
#print axioms StagedDense.a786
#print axioms StagedDense.a782
#print axioms StagedDense.a774
#print axioms StagedDense.a760
#print axioms StagedDense.a793
#print axioms StagedDense.a794
#print axioms StagedDense.a792
#print axioms StagedDense.a796
#print axioms StagedDense.a797
#print axioms StagedDense.a795
#print axioms StagedDense.a791
#print axioms StagedDense.a800
#print axioms StagedDense.a801
#print axioms StagedDense.a799
#print axioms StagedDense.a803
#print axioms StagedDense.a804
#print axioms StagedDense.a802
#print axioms StagedDense.a798
#print axioms StagedDense.a790
#print axioms StagedDense.a808
#print axioms StagedDense.a809
#print axioms StagedDense.a807
#print axioms StagedDense.a811
#print axioms StagedDense.a812
#print axioms StagedDense.a810
#print axioms StagedDense.a806
#print axioms StagedDense.a815
#print axioms StagedDense.a816
#print axioms StagedDense.a814
#print axioms StagedDense.a818
#print axioms StagedDense.a819
#print axioms StagedDense.a817
#print axioms StagedDense.a813
#print axioms StagedDense.a805
#print axioms StagedDense.a789
#print axioms StagedDense.a759
#print axioms StagedDense.a825
#print axioms StagedDense.a826
#print axioms StagedDense.a824
#print axioms StagedDense.a828
#print axioms StagedDense.a829
#print axioms StagedDense.a827
#print axioms StagedDense.a823
#print axioms StagedDense.a832
#print axioms StagedDense.a833
#print axioms StagedDense.a831
#print axioms StagedDense.a835
#print axioms StagedDense.a836
#print axioms StagedDense.a834
#print axioms StagedDense.a830
#print axioms StagedDense.a822
#print axioms StagedDense.a840
#print axioms StagedDense.a841
#print axioms StagedDense.a839
#print axioms StagedDense.a843
#print axioms StagedDense.a844
#print axioms StagedDense.a842
#print axioms StagedDense.a838
#print axioms StagedDense.a847
#print axioms StagedDense.a848
#print axioms StagedDense.a846
#print axioms StagedDense.a850
#print axioms StagedDense.a851
#print axioms StagedDense.a849
#print axioms StagedDense.a845
#print axioms StagedDense.a837
#print axioms StagedDense.a821
#print axioms StagedDense.a856
#print axioms StagedDense.a857
#print axioms StagedDense.a855
#print axioms StagedDense.a859
#print axioms StagedDense.a860
#print axioms StagedDense.a858
#print axioms StagedDense.a854
#print axioms StagedDense.a863
#print axioms StagedDense.a864
#print axioms StagedDense.a862
#print axioms StagedDense.a866
#print axioms StagedDense.a867
#print axioms StagedDense.a865
#print axioms StagedDense.a861
#print axioms StagedDense.a853
#print axioms StagedDense.a871
#print axioms StagedDense.a872
#print axioms StagedDense.a870
#print axioms StagedDense.a874
#print axioms StagedDense.a875
#print axioms StagedDense.a873
#print axioms StagedDense.a869
#print axioms StagedDense.a878
#print axioms StagedDense.a879
#print axioms StagedDense.a877
#print axioms StagedDense.a881
#print axioms StagedDense.a882
#print axioms StagedDense.a880
#print axioms StagedDense.a876
#print axioms StagedDense.a868
#print axioms StagedDense.a852
#print axioms StagedDense.a820
#print axioms StagedDense.a758
#print axioms StagedDense.a642
#print axioms StagedDense.pipe
#print axioms StagedDense.result
#print axioms PCSDD.Controls.isum_of_plan
