"""Bind the shipped mission JSON to Lean constants; this is a checked generator,
not a proof of JSON parsing or of Python/JavaScript refinement.
"""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PIN = "d3b02eb4eb39976fd3179a44ef1b6bffd17a8f4a271b1bd7cddb97eb71276df2"


def formula(node, ctx=()):
    if not isinstance(node, dict):
        raise ValueError("Formula must be an object")
    op = node.get("op")
    fields = {"pred": {"op", "p", "x"}, "rel": {"op", "x", "y"},
              "not": {"op", "f"}, "and": {"op", "a", "b"},
              "or": {"op", "a", "b"}, "imp": {"op", "a", "b"},
              "forall": {"op", "x", "f"}, "exists": {"op", "x", "f"}}
    if op not in fields or set(node) != fields[op]:
        raise ValueError("Unknown operator or fields")
    def name(key):
        value = node[key]
        if not isinstance(value, str) or not value.isascii() or not value.isidentifier():
            raise ValueError("Unsupported name")
        return value
    def variable(key):
        value = name(key)
        if value not in ctx:
            raise ValueError("Unbound variable")
        return json.dumps(value), str(ctx.index(value))
    if op == "pred":
        p = name("p")
        if p not in {"P", "Q"}:
            raise ValueError("Unknown predicate")
        x, i = variable("x")
        return f'(.pred "{p}" {x})', f"(.pred .{p} {i})"
    if op == "rel":
        x, i = variable("x"); y, j = variable("y")
        return f"(.rel {x} {y})", f"(.rel {i} {j})"
    if op in {"forall", "exists"}:
        x = name("x"); a, b = formula(node["f"], (x, *ctx))
        tag = "all" if op == "forall" else "ex"
        return f"(.{tag} {json.dumps(x)} {a})", f"(.{tag} {b})"
    if op == "not":
        a, b = formula(node["f"], ctx)
        return f"(.not {a})", f"(.not {b})"
    a, b = formula(node["a"], ctx); c, d = formula(node["b"], ctx)
    return f"(.{op} {a} {c})", f"(.{op} {b} {d})"


def render():
    rows = json.loads((ROOT / "pcs/schemas/countermodel_missions_v1.json").read_text())
    raw = json.dumps(rows, ensure_ascii=False, separators=(",", ":")).encode()
    if hashlib.sha256(raw).hexdigest() != PIN or len(rows) != 7:
        raise ValueError("Mission ruleset pin mismatch")
    out = ['-- Generated by scripts/generate_countermodel_missions.py; checked in CI.',
           'import PCSCountermodel.Fixtures', '', 'namespace PCSCountermodel.Missions',
           f'def rulesetSHA256 : String := "{PIN}"', '']
    audits = []
    for i, row in enumerate(rows):
        a, at = formula(row["a"]); b, bt = formula(row["b"])
        out += [f'-- {row["id"]}', f'def leftN{i} : NFormula := {a}',
                f'def rightN{i} : NFormula := {b}', f'def left{i} : Formula 0 := {at}',
                f'def right{i} : Formula 0 := {bt}',
                f'theorem lowering{i} : lower [] leftN{i} = some left{i} ∧',
                f'    lower [] rightN{i} = some right{i} := ⟨rfl, rfl⟩']
        # Concrete witnesses are kernel checked; minimality uses the general search theorem.
        n, mask = [(2, 1), (1, 1), (1, 1), (1, 1), (1, 0), (2, 144), (2, 96)][i]
        out += [f'theorem witness{i} : checker (worldOfBits {n} {mask}) left{i} right{i} = true := by decide',
                f'theorem disagreement{i} (ρ : String → Fin {n}) :',
                f'    ¬ (NHolds (worldOfBits {n} {mask}) ρ leftN{i} ↔',
                f'       NHolds (worldOfBits {n} {mask}) ρ rightN{i}) :=',
                f'  (namedChecker_sound _ (c := true) (by decide) ρ).mp rfl',
                f'theorem minimum{i} : (search left{i} right{i}).map Sigma.fst = some {n} := by decide', '']
        audits += [f'#print axioms {tag}{i}' for tag in ('lowering', 'witness', 'disagreement', 'minimum')]
    out += ['def missions : List (String × NFormula × NFormula) := [']
    out += [f'  ({json.dumps(row["id"])}, leftN{i}, rightN{i})' + (',' if i < 6 else '') for i, row in enumerate(rows)]
    out += [']', *audits, 'end PCSCountermodel.Missions', '']
    return '\n'.join(out)


def main():
    parser = argparse.ArgumentParser(); parser.add_argument('--write', action='store_true')
    args = parser.parse_args()
    path = ROOT / 'formal/PCSCountermodel/Missions.lean'
    expected = render()
    if args.write:
        path.write_text(expected)
    elif path.read_text() != expected:
        raise SystemExit('Lean mission constants differ from the pinned game ruleset')
    print('COUNTERMODEL_MISSION_BINDINGS_PASS: 7 pinned AST pairs')


if __name__ == '__main__':
    main()
