import PCS.V2.ReceiptAuthorityV3
import PCS.V2.TranslationV3
import PCS.V2.ReceiptThreatModelV3
import PCS.V2.TranslationV3Json
import PCS.V2.LeanSyntaxV3
import PCS.V2.AssuranceV3
import PCS.V2.EntailmentV3
import PCS.V2.CertiForgeAdapterV1

/-! Axiom audit of PCS Proof-Carrying Semantic Intelligence v3 (printed on every build).
    Every theorem of the v3 modules is listed.  Expected: only `propext`, `Classical.choice`,
    `Quot.sound` (or a subset); never `sorryAx`, `Lean.ofReduceBool` or a project axiom.
    Checked mechanically by tools/check_semantic_v3_audit.sh.
    Generated by tools/gen_semantic_v3_audit.py. -/

-- ReceiptAuthorityV3
#print axioms PCS.V2.Semantic.V3.coreDiagnostics_nil
#print axioms PCS.V2.Semantic.V3.mem_dedup
#print axioms PCS.V2.Semantic.V3.dedup_nodup
#print axioms PCS.V2.Semantic.V3.mem_issuersOf
#print axioms PCS.V2.Semantic.V3.acceptEnvelope_ok_iff
#print axioms PCS.V2.Semantic.V3.acceptEnvelope_error_congr
#print axioms PCS.V2.Semantic.V3.acceptAllV3_ok_iff
#print axioms PCS.V2.Semantic.V3.acceptAllV3_congr
#print axioms PCS.V2.Semantic.V3.quorumFailure_none_iff
#print axioms PCS.V2.Semantic.V3.receiptPhase_ok_iff
#print axioms PCS.V2.Semantic.V3.receiptPhase_ok_nonces
#print axioms PCS.V2.Semantic.V3.receiptPhase_sound
#print axioms PCS.V2.Semantic.V3.receiptPhase_complete
#print axioms PCS.V2.Semantic.V3.receiptPhase_consumed_congr
-- TranslationV3
#print axioms PCS.V2.Semantic.V3.legacyDiagnostics_nil
#print axioms PCS.V2.Semantic.V3.classifyV3_certified
#print axioms PCS.V2.Semantic.V3.classifyV3_of
#print axioms PCS.V2.Semantic.V3.decideV3_outcome
#print axioms PCS.V2.Semantic.V3.decideV3_certified_sound
#print axioms PCS.V2.Semantic.V3.semanticAnalysis_linked_of
#print axioms PCS.V2.Semantic.V3.decideV3_certified_complete
#print axioms PCS.V2.Semantic.V3.decideV3_certified_iff
#print axioms PCS.V2.Semantic.V3.stateful_authority_refines_specification
#print axioms PCS.V2.Semantic.V3.decideV3_certified_preserves_denotation
#print axioms PCS.V2.Semantic.V3.decideV3_consumed
#print axioms PCS.V2.Semantic.V3.stepV3_ledger
#print axioms PCS.V2.Semantic.V3.stepV3_rejected_no_consumption
#print axioms PCS.V2.Semantic.V3.stepV3_monotone
#print axioms PCS.V2.Semantic.V3.stepV3_replay_rejected
#print axioms PCS.V2.Semantic.V3.stepV3_consumed_nodup
#print axioms PCS.V2.Semantic.V3.runV3_consumed_nodup
#print axioms PCS.V2.Semantic.V3.runV3_consumed_mem
#print axioms PCS.V2.Semantic.V3.runV3_ledger
#print axioms PCS.V2.Semantic.V3.runV3_no_double_consumption
-- ReceiptThreatModelV3
#print axioms PCS.V2.Semantic.V3.decideV3_consumed_congr
#print axioms PCS.V2.Semantic.V3.decideV3_restrict
#print axioms PCS.V2.Semantic.V3.replayed_receipt_rejected
#print axioms PCS.V2.Semantic.V3.expired_receipt_rejected
#print axioms PCS.V2.Semantic.V3.future_receipt_rejected
#print axioms PCS.V2.Semantic.V3.revoked_key_rejected
#print axioms PCS.V2.Semantic.V3.inactive_key_rejected
#print axioms PCS.V2.Semantic.V3.pre_genesis_receipt_rejected
#print axioms PCS.V2.Semantic.V3.unknown_version_receipt_rejected
#print axioms PCS.V2.Semantic.V3.forged_signature_rejected
#print axioms PCS.V2.Semantic.V3.duplicate_nonce_in_request_rejected
#print axioms PCS.V2.Semantic.V3.role_substitution_rejected
#print axioms PCS.V2.Semantic.V3.encContext_inj
#print axioms PCS.V2.Semantic.V3.proofStatement_inj
#print axioms PCS.V2.Semantic.V3.elaborationStatement_inj
#print axioms PCS.V2.Semantic.V3.confirmationStatement_inj
#print axioms PCS.V2.Semantic.V3.statements_domain_separated
#print axioms PCS.V2.Semantic.V3.cross_context_receipt_rejected
#print axioms PCS.V2.Semantic.V3.statement_replacement_rejected
#print axioms PCS.V2.Semantic.V3.legacy_receipt_rejected
#print axioms PCS.V2.Semantic.V3.quorum_not_met_rejected
#print axioms PCS.V2.Semantic.V3.missing_confirmation_rejected
#print axioms PCS.V2.Semantic.V3.missing_proof_rejected
#print axioms PCS.V2.Semantic.V3.decideV3_ignores_proposer_metadata
#print axioms PCS.V2.Semantic.V3.certified_receipt_assurance
#print axioms PCS.V2.Semantic.V3.certified_receipt_quorum_assurance
#print axioms PCS.V2.Semantic.V3.certified_kernel_check_record
-- TranslationV3Json
#print axioms PCS.V2.Semantic.V3.decRole_name
#print axioms PCS.V2.Semantic.V3.decEnvelope_enc
#print axioms PCS.V2.Semantic.V3.decRequestV3_enc
#print axioms PCS.V2.Semantic.V3.decKeyEntry_enc
#print axioms PCS.V2.Semantic.V3.decRegistry_encRegistry
#print axioms PCS.V2.Semantic.V3.decAuthorityConfigV3_enc
#print axioms PCS.V2.Semantic.V3.decLedgerSnapshot_enc
#print axioms PCS.V2.Semantic.V3.semanticCheckV3_step
#print axioms PCS.V2.Semantic.V3.semanticCheckV3_encRequestV3
#print axioms PCS.V2.Semantic.V3.semanticCheckV3_malformed_rejected
#print axioms PCS.V2.Semantic.V3.semanticCheckV3_certified_sound
#print axioms PCS.V2.Semantic.V3.semanticCheckV3_ledger_delta
-- LeanSyntaxV3
#print axioms PCS.V2.Semantic.LeanSyntax.print_readTerm
#print axioms PCS.V2.Semantic.LeanSyntax.printArgs_readTerms
#print axioms PCS.V2.Semantic.LeanSyntax.print_readFormula
#print axioms PCS.V2.Semantic.LeanSyntax.renderClaimLean_eq_print
#print axioms PCS.V2.Semantic.LeanSyntax.notMem_of_protected
#print axioms PCS.V2.Semantic.LeanSyntax.globalIn_of_protected
#print axioms PCS.V2.Semantic.LeanSyntax.contains_of_freeVars_nil
#print axioms PCS.V2.Semantic.LeanSyntax.res_readTerm
#print axioms PCS.V2.Semantic.LeanSyntax.resList_readTerms
#print axioms PCS.V2.Semantic.LeanSyntax.update_ne
#print axioms PCS.V2.Semantic.LeanSyntax.denote_readFormula
#print axioms PCS.V2.Semantic.LeanSyntax.foldr_imp_iff
#print axioms PCS.V2.Semantic.LeanSyntax.Term.freeVars_mono
#print axioms PCS.V2.Semantic.LeanSyntax.Term.freeVarsList_mono
#print axioms PCS.V2.Semantic.LeanSyntax.Formula.freeVars_mono
#print axioms PCS.V2.Semantic.LeanSyntax.denoteBinders_readClaim
#print axioms PCS.V2.Semantic.LeanSyntax.lean_reading_correspondence_N
#print axioms PCS.V2.Semantic.LeanSyntax.Registry.resolve_mem
#print axioms PCS.V2.Semantic.LeanSyntax.Registry.resolveSort_mem
#print axioms PCS.V2.Semantic.LeanSyntax.protected_of_registry_name
#print axioms PCS.V2.Semantic.LeanSyntax.lean_reading_correspondence
#print axioms PCS.V2.Semantic.LeanSyntax.gate_rejects_reserved_binder
#print axioms PCS.V2.Semantic.LeanSyntax.capture_breaks_correspondence
-- AssuranceV3
#print axioms PCS.V2.Semantic.V3.encClaim_injective
#print axioms PCS.V2.Semantic.V3.encAmbiguities_injective
#print axioms PCS.V2.Semantic.V3.confirmationStatement_identifies
#print axioms PCS.V2.Semantic.V3.elaboration_record_is_not_proof
#print axioms PCS.V2.Semantic.V3.certified_translation_holds_in_environment
#print axioms PCS.V2.Semantic.V3.pcs_v3_certified_wire_assurance
-- EntailmentV3
#print axioms PCS.V2.Semantic.Formula.iff_denote
#print axioms PCS.V2.Semantic.entailsF_sound
#print axioms PCS.V2.Semantic.entails_sound
#print axioms PCS.V2.Semantic.conjAll_denote
#print axioms PCS.V2.Semantic.ndenoteParams_mono
#print axioms PCS.V2.Semantic.NClaim.strengthens_sound
#print axioms PCS.V2.Semantic.strengthens_sound
#print axioms PCS.V2.Semantic.V3.strengthening_statement_ne_confirmation
#print axioms PCS.V2.Semantic.V3.decideStrengtheningV3_sound
#print axioms PCS.V2.Semantic.V3.stepStrengtheningV3_rejected_no_consumption
#print axioms PCS.V2.Semantic.V3.ordinary_confirmation_cannot_authorize_strengthening
#print axioms PCS.V2.Semantic.V3.strengthenCheckV3_certified_sound
#print axioms PCS.V2.Semantic.V3.strengthening_is_not_equivalence
-- CertiForgeAdapterV1
#print axioms PCS.V2.CertiForge.ProgEquiv.refl
#print axioms PCS.V2.CertiForge.ProgEquiv.symm
#print axioms PCS.V2.CertiForge.ProgEquiv.trans
#print axioms PCS.V2.CertiForge.progEquiv_property_transfer
#print axioms PCS.V2.CertiForge.chain_equiv
#print axioms PCS.V2.CertiForge.cost_not_invariant
#print axioms PCS.V2.CertiForge.mem_allBV
#print axioms PCS.V2.CertiForge.mem_allInputs
#print axioms PCS.V2.CertiForge.exhaustiveEquivB_sound
#print axioms PCS.V2.CertiForge.refutesB_sound
#print axioms PCS.V2.CertiForge.cfStatement_ne_proofStatement
#print axioms PCS.V2.CertiForge.unsupported_semantics_rejected
#print axioms PCS.V2.CertiForge.decideCF_pcsChecked_sound
#print axioms PCS.V2.CertiForge.decideCF_attested_receipts
#print axioms PCS.V2.CertiForge.decideCF_attested_sound
#print axioms PCS.V2.CertiForge.counterexample_overrides_receipts
#print axioms PCS.V2.CertiForge.decideCF_ignores_improvement
#print axioms PCS.V2.CertiForge.certified_chain_property_transfer
#print axioms PCS.V2.CertiForge.Examples.mulTwo_shlOne_pcs_checked
#print axioms PCS.V2.CertiForge.Examples.mulTwo_equiv_shlOne
#print axioms PCS.V2.CertiForge.Examples.mulTwo_addOne_refuted
#print axioms PCS.V2.CertiForge.Examples.effectful_claim_unsupported
#print axioms PCS.V2.CertiForge.Examples.no_improvement_claimed_correctly
