import PCS.V2.SemanticEquiv
import PCS.V2.FiniteModel
import PCS.V2.CertSearch
import PCS.V2.TranslationV2
import PCS.V2.TranslationV2Json
import PCS.V2.SemanticFeedback
import PCS.V2.SemanticLimits
import PCS.V2.SemanticV2Fixtures
import PCS.V2.SemanticCompose
import PCS.V2.ReceiptLedger
import PCS.V2.CNL
import PCS.V2.SemanticV2LeanModel

/-! Axiom audit of PCS Proof-Carrying Semantic Intelligence v2 (printed on every build).
    Every theorem of the v2 modules is listed.  Expected: only `propext`, `Classical.choice`,
    `Quot.sound` (or a subset); never `sorryAx`, `Lean.ofReduceBool` or a project axiom.
    Generated by tools/gen_semantic_v2_audit.py. -/

-- SemanticEquiv
#print axioms PCS.V2.Semantic.NFormula.SemEquiv.refl
#print axioms PCS.V2.Semantic.NFormula.SemEquiv.symm
#print axioms PCS.V2.Semantic.NFormula.SemEquiv.trans
#print axioms PCS.V2.Semantic.NTerm.swapBV_denote
#print axioms PCS.V2.Semantic.NTerm.swapBVList_denote
#print axioms PCS.V2.Semantic.consEnv_swapIdx
#print axioms PCS.V2.Semantic.NFormula.swapBV_denote
#print axioms PCS.V2.Semantic.consEnv_swap0
#print axioms PCS.V2.Semantic.quantSwap_sound
#print axioms PCS.V2.Semantic.Rule.apply_sound
#print axioms PCS.V2.Semantic.option_map_eq_some
#print axioms PCS.V2.Semantic.rewriteAt_sound
#print axioms PCS.V2.Semantic.NClaim.SemEquiv.refl
#print axioms PCS.V2.Semantic.NClaim.SemEquiv.symm
#print axioms PCS.V2.Semantic.NClaim.SemEquiv.trans
#print axioms PCS.V2.Semantic.forall_mem_set_iff
#print axioms PCS.V2.Semantic.NClaim.applyStep_sound
#print axioms PCS.V2.Semantic.NClaim.applySteps_sound
#print axioms PCS.V2.Semantic.checkCert_sound
#print axioms PCS.V2.Semantic.translation_certificate_sound
#print axioms PCS.V2.Semantic.certificate_acceptance_implies_semantic_preservation
#print axioms PCS.V2.Semantic.certificate_checker_rejects_invalid_derivations
#print axioms PCS.V2.Semantic.inequivalent_claims_admit_no_certificate
#print axioms PCS.V2.Semantic.untrusted_translation_search_cannot_forge_certified_equivalence
#print axioms PCS.V2.Semantic.checkCert_empty
-- FiniteModel
#print axioms PCS.V2.Semantic.NTerm.evalF_eq
#print axioms PCS.V2.Semantic.NTerm.evalFList_eq
#print axioms PCS.V2.Semantic.NFormula.evalF_iff
#print axioms PCS.V2.Semantic.evalParams_iff
#print axioms PCS.V2.Semantic.NClaim.evalF_iff
#print axioms PCS.V2.Semantic.finite_evaluator_sound
#print axioms PCS.V2.Semantic.finite_evaluator_complete_for_supported_finite_models
#print axioms PCS.V2.Semantic.FinModel.mem_tuples
#print axioms PCS.V2.Semantic.Registry.resolve_mem
#print axioms PCS.V2.Semantic.conformsB_sound
#print axioms PCS.V2.Semantic.inhabitedB_sound
#print axioms PCS.V2.Semantic.claim_evalF_iff
#print axioms PCS.V2.Semantic.countermodel_witness_sound
#print axioms PCS.V2.Semantic.countermodel_demonstrates_semantic_difference
#print axioms PCS.V2.Semantic.countermodel_witness_inhabited
#print axioms PCS.V2.Semantic.countermodel_refutes_inhabited_equivalence
#print axioms PCS.V2.Semantic.countermodel_excludes_certificate
#print axioms PCS.V2.Semantic.mkCarriers_size
#print axioms PCS.V2.Semantic.mem_vecsSum
#print axioms PCS.V2.Semantic.searchLoop_found
#print axioms PCS.V2.Semantic.searchLoop_exhausted
#print axioms PCS.V2.Semantic.orderedSizeVectors_pairwise
#print axioms PCS.V2.Semantic.modelsFor_domainSize
#print axioms PCS.V2.Semantic.orderedSizeVectors_length
#print axioms PCS.V2.Semantic.mem_vecsSum_pos
#print axioms PCS.V2.Semantic.mkCarriers_find
#print axioms PCS.V2.Semantic.searchClass_inhabited
#print axioms PCS.V2.Semantic.search_found_sound
#print axioms PCS.V2.Semantic.search_found_minimal
#print axioms PCS.V2.Semantic.search_exhausted_complete
-- CertSearch
#print axioms PCS.V2.Semantic.findCheckedCert_checked
-- TranslationV2
#print axioms PCS.V2.Semantic.accepted_translation_preserves_denotation_v2
#print axioms PCS.V2.Semantic.accepted_explanation_means_interpretation_v2
#print axioms PCS.V2.Semantic.v1_acceptance_implies_v2_contract
#print axioms PCS.V2.Semantic.countermodel_refutes_contract_v2
#print axioms PCS.V2.Semantic.countermodel_v1_rejected
#print axioms PCS.V2.Semantic.countermodel_and_certificate_exclusive
#print axioms PCS.V2.Semantic.checkExplanationV2_nil
#print axioms PCS.V2.Semantic.gateDiagnostics_nil
#print axioms PCS.V2.Semantic.countermodelPhase_not_linked
#print axioms PCS.V2.Semantic.semanticAnalysis_linked
#print axioms PCS.V2.Semantic.decideV2_certified_gates
#print axioms PCS.V2.Semantic.decideV2_certified_sound
#print axioms PCS.V2.Semantic.decideV2_certified_complete
#print axioms PCS.V2.Semantic.executable_semantic_checker_refines_specification
#print axioms PCS.V2.Semantic.decideV2_certified_iff
#print axioms PCS.V2.Semantic.decideV2_certified_preserves_denotation
#print axioms PCS.V2.Semantic.countermodelPhase_sound
#print axioms PCS.V2.Semantic.semanticAnalysis_counterexample_sound
#print axioms PCS.V2.Semantic.decideV2_counterexample_sound
#print axioms PCS.V2.Semantic.decideV2_ambiguity_not_certified
#print axioms PCS.V2.Semantic.decideV2_unconfirmed_not_certified
#print axioms PCS.V2.Semantic.decideV2_ungrounded_not_certified
#print axioms PCS.V2.Semantic.decideV2_unsupported_not_certified
#print axioms PCS.V2.Semantic.decideV2_missing_proof_not_certified
#print axioms PCS.V2.Semantic.decideV2_inequivalent_not_certified
#print axioms PCS.V2.Semantic.semantic_authority_does_not_trust_proposer_metadata
#print axioms PCS.V2.Semantic.pcs_proof_carrying_translation_sound_v2
-- TranslationV2Json
#print axioms PCS.V2.Semantic.decNat_encNat
#print axioms PCS.V2.Semantic.decNats_encNats
#print axioms PCS.V2.Semantic.decRule_encRule
#print axioms PCS.V2.Semantic.decTarget_encTarget
#print axioms PCS.V2.Semantic.decStep_encStep
#print axioms PCS.V2.Semantic.decSteps_encSteps
#print axioms PCS.V2.Semantic.decCert_encCert
#print axioms PCS.V2.Semantic.decFinModel_enc
#print axioms PCS.V2.Semantic.decCountermodel_enc
#print axioms PCS.V2.Semantic.decBounds_encBounds
#print axioms PCS.V2.Semantic.semantic_wire_roundtrip
#print axioms PCS.V2.Semantic.decRequestV2_encRequestV2
#print axioms PCS.V2.Semantic.semanticCheckV2_decision
#print axioms PCS.V2.Semantic.semanticCheckV2_encRequestV2
#print axioms PCS.V2.Semantic.semanticCheckV2_certified_sound
#print axioms PCS.V2.Semantic.accepted_wire_translation_preserves_semantics
#print axioms PCS.V2.Semantic.malformed_wire_request_rejected
#print axioms PCS.V2.Semantic.semantic_authority_cannot_be_bypassed_by_unsigned_receipts
#print axioms PCS.V2.Semantic.decCountermodelBundle_enc
#print axioms PCS.V2.Semantic.countermodel_bundle_sound
-- SemanticFeedback
#print axioms PCS.V2.Semantic.human_obligations_not_mechanical
#print axioms PCS.V2.Semantic.labelOf_positive
#print axioms PCS.V2.Semantic.labelOf_negative
#print axioms PCS.V2.Semantic.label_positive_sound
#print axioms PCS.V2.Semantic.label_negative_sound
-- SemanticLimits
#print axioms PCS.V2.Semantic.Limits.search_exhausted_at_two
#print axioms PCS.V2.Semantic.Limits.three_element_countermodel
#print axioms PCS.V2.Semantic.Limits.no_countermodel_found_within_bound_is_not_equivalence_proof
#print axioms PCS.V2.Semantic.Limits.conjCert_checks
#print axioms PCS.V2.Semantic.Limits.structural_rejection_is_not_semantic_inequivalence
#print axioms PCS.V2.Semantic.Limits.intent_gap
#print axioms PCS.V2.Semantic.Limits.registry_name_does_not_fix_meaning
-- SemanticV2Fixtures
#print axioms PCS.V2.Semantic.FixturesV2.revCert_checks
#print axioms PCS.V2.Semantic.FixturesV2.reproCert_checks
#print axioms PCS.V2.Semantic.FixturesV2.bioCert_checks
#print axioms PCS.V2.Semantic.FixturesV2.rev_certified
#print axioms PCS.V2.Semantic.FixturesV2.repro_certified
#print axioms PCS.V2.Semantic.FixturesV2.bio_certified
#print axioms PCS.V2.Semantic.FixturesV2.rev_v1_rejects
#print axioms PCS.V2.Semantic.FixturesV2.repro_v1_rejects
#print axioms PCS.V2.Semantic.FixturesV2.bio_v1_rejects
#print axioms PCS.V2.Semantic.FixturesV2.rev_preserves_denotation
#print axioms PCS.V2.Semantic.FixturesV2.revExists_countermodel
#print axioms PCS.V2.Semantic.FixturesV2.revTime_countermodel
#print axioms PCS.V2.Semantic.FixturesV2.revDropped_countermodel
#print axioms PCS.V2.Semantic.FixturesV2.revOr_countermodel
#print axioms PCS.V2.Semantic.FixturesV2.revNeg_countermodel
#print axioms PCS.V2.Semantic.FixturesV2.reproConverse_countermodel
#print axioms PCS.V2.Semantic.FixturesV2.heldOut_countermodel
#print axioms PCS.V2.Semantic.FixturesV2.bioOr_countermodel
#print axioms PCS.V2.Semantic.FixturesV2.bioLegacy_countermodel
#print axioms PCS.V2.Semantic.FixturesV2.never_certified_of_countermodel
#print axioms PCS.V2.Semantic.FixturesV2.revExists_never_certified
#print axioms PCS.V2.Semantic.FixturesV2.revTime_never_certified
#print axioms PCS.V2.Semantic.FixturesV2.forged_certificate_rejected
#print axioms PCS.V2.Semantic.FixturesV2.ambiguous_needs_clarification
#print axioms PCS.V2.Semantic.FixturesV2.forged_confirmation_invalid
#print axioms PCS.V2.Semantic.FixturesV2.missing_proof_unresolved
#print axioms PCS.V2.Semantic.FixturesV2.unsupported_fragment
-- SemanticCompose
#print axioms PCS.V2.Semantic.SemEquiv.not_congr
#print axioms PCS.V2.Semantic.SemEquiv.and_congr
#print axioms PCS.V2.Semantic.SemEquiv.or_congr
#print axioms PCS.V2.Semantic.SemEquiv.imp_congr
#print axioms PCS.V2.Semantic.SemEquiv.quant_congr
#print axioms PCS.V2.Semantic.ndenoteParams_and
#print axioms PCS.V2.Semantic.NClaim.conj_denote
#print axioms PCS.V2.Semantic.compositional_translation_sound
#print axioms PCS.V2.Semantic.compositional_certificates_sound
#print axioms PCS.V2.Semantic.certified_repair_preserves_meaning
#print axioms PCS.V2.Semantic.certified_rewriting_cannot_repair_mistranslation
#print axioms PCS.V2.Semantic.cachedCheck_sound
#print axioms PCS.V2.Semantic.stale_cache_cannot_be_reused
#print axioms PCS.V2.Semantic.semantic_obligation_graph_acceptance_sound
#print axioms PCS.V2.Semantic.wire_obligation_graph_acceptance_sound
-- ReceiptLedger
#print axioms PCS.V2.Semantic.Ledger.ReceiptRole.name_injective
#print axioms PCS.V2.Semantic.Ledger.utf8_flatMap_injective
#print axioms PCS.V2.Semantic.Ledger.envelopeBytes_injective
#print axioms PCS.V2.Semantic.Ledger.acceptEnvelope_sound
#print axioms PCS.V2.Semantic.Ledger.replay_rejected
#print axioms PCS.V2.Semantic.Ledger.expired_rejected
#print axioms PCS.V2.Semantic.Ledger.revoked_rejected
#print axioms PCS.V2.Semantic.Ledger.role_mismatch_rejected
#print axioms PCS.V2.Semantic.Ledger.unknown_version_rejected
#print axioms PCS.V2.Semantic.Ledger.statement_substitution_rejected
#print axioms PCS.V2.Semantic.Ledger.role_confusion_and_substitution_impossible
-- CNL
#print axioms PCS.V2.Semantic.CNL.Term.toks_head
#print axioms PCS.V2.Semantic.CNL.parseTerm_toks
#print axioms PCS.V2.Semantic.CNL.parseTerms_toks
#print axioms PCS.V2.Semantic.CNL.parseFormula_toks
#print axioms PCS.V2.Semantic.CNL.parseTerm_inv
#print axioms PCS.V2.Semantic.CNL.parseTerms_inv
#print axioms PCS.V2.Semantic.CNL.brk_inv
#print axioms PCS.V2.Semantic.CNL.parseFormula_inv
#print axioms PCS.V2.Semantic.CNL.Term.size_le_toks
#print axioms PCS.V2.Semantic.CNL.Term.sizeList_le_toks
#print axioms PCS.V2.Semantic.CNL.Formula.size_le_toks
#print axioms PCS.V2.Semantic.CNL.Formula.toks_ne_nil
#print axioms PCS.V2.Semantic.CNL.Kw.wordTok_word
#print axioms PCS.V2.Semantic.CNL.Kw.word_no_space
#print axioms PCS.V2.Semantic.CNL.Kw.mem_all
#print axioms PCS.V2.Semantic.CNL.word_wordTok
#print axioms PCS.V2.Semantic.CNL.wordTok_word_of_valid
#print axioms PCS.V2.Semantic.CNL.word_no_space_of_valid
#print axioms PCS.V2.Semantic.CNL.parseWords_renderWords
#print axioms PCS.V2.Semantic.CNL.renderWords_parseWords
#print axioms PCS.V2.Semantic.CNL.controlled_language_print_parse
#print axioms PCS.V2.Semantic.CNL.controlled_language_parse_print
#print axioms PCS.V2.Semantic.CNL.controlled_language_render_preserves_semantics
#print axioms PCS.V2.Semantic.CNL.renderCNL_injective
#print axioms PCS.V2.Semantic.CNL.explanation_preserves_quantifier_scope
#print axioms PCS.V2.Semantic.CNL.explanation_preserves_assumptions
#print axioms PCS.V2.Semantic.CNL.explanation_preserves_grounded_definitions
#print axioms PCS.V2.Semantic.CNL.explanation_preserves_proof_limitations
-- SemanticV2LeanModel
#print axioms PCS.V2.Semantic.LeanModel.forall_time
#print axioms PCS.V2.Semantic.LeanModel.forall_action
#print axioms PCS.V2.Semantic.LeanModel.forall_run
#print axioms PCS.V2.Semantic.LeanModel.forall_residue
#print axioms PCS.V2.Semantic.LeanModel.leanModel_conforms
#print axioms PCS.V2.Semantic.LeanModel.rev_interpretation_lean_meaning
#print axioms PCS.V2.Semantic.LeanModel.rev_candidate_lean_meaning
#print axioms PCS.V2.Semantic.LeanModel.repro_interpretation_lean_meaning
#print axioms PCS.V2.Semantic.LeanModel.repro_candidate_lean_meaning
#print axioms PCS.V2.Semantic.LeanModel.bio_interpretation_lean_meaning
#print axioms PCS.V2.Semantic.LeanModel.bio_candidate_lean_meaning
#print axioms PCS.V2.Semantic.LeanModel.rev_certified_lean_statements_equivalent
#print axioms PCS.V2.Semantic.LeanModel.repro_certified_lean_statements_equivalent
#print axioms PCS.V2.Semantic.LeanModel.bio_certified_lean_statements_equivalent
